"""Pure-Python zstd decompressor — last-resort fallback.

A complete, stdlib-only zstd *decompressor* sufficient to read the
frames that restic / rustic emit (rustic v2 repos are zstd-compressed
by default).  It exists so that tier-3 recovery — the bundled-CPython +
``standalone_restorer.py`` last resort — can decompress repository
blobs decades from now on ANY architecture / CPython minor, with the
``zstandard`` package absent and no stdlib ``compression.zstd`` (which
landed only in CPython 3.14).

**Performance:** Pure-Python entropy decoding is roughly ~1 MB/s — on
par with the pure-Python AES path it sits behind, and acceptable for a
manual emergency restore.  When the ``zstandard`` package IS importable,
``restic_fallback`` uses it instead (~100× faster); this module is the
fallback backend.

Scope (intentionally narrow — decompression only):
    * Single-frame zstd input (the form restic/rustic blobs take).
    * Raw, RLE, and Compressed blocks.
    * Huffman literals (4-stream and single-stream), FSE + repeat /
      RLE / direct literal-length, match-length and offset code modes.
    * Repeat-offset history per RFC 8878 §3.1.1.5.
    * Optional 4-byte XXH64 frame checksum (verified when present).
    * Dictionaries are rejected loudly (restic does not use them).

References:
    * RFC 8878 — Zstandard Compression and the application/zstd Media Type
    * https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md
"""

from __future__ import annotations

import struct

_MAGIC = 0xFD2FB528

# Predefined distributions (RFC 8878 §3.1.1.3.2.2) — used when a
# sequence FSE table is in "Predefined_Mode".  These exact symbol /
# baseline / num-bit assignments are taken verbatim from the vendored
# upstream zstd v1.5.6 decoder (``recovery/vendored/zstd``,
# ``LL_defaultDTable`` / ``OF_defaultDTable`` / ``ML_defaultDTable``).
# We reuse the C decoder's pre-spread tables rather than re-deriving them
# because the predefined tables were generated by zstd's own build-time
# tool, whose symbol spread differs subtly from the runtime FSE table
# build used for FSE_Compressed_Mode (only the latter is reproduced by
# ``_build_seq_dtable`` below).  Each row is
# ``(newstate_baseline, add_bits, state_nbits, symbol_base_value)``.

_LL_PREDEF: tuple[tuple[int, int, int, int], ...] = (
    (0, 0, 4, 0), (16, 0, 4, 0), (32, 0, 5, 1), (0, 0, 5, 3),
    (0, 0, 5, 4), (0, 0, 5, 6), (0, 0, 5, 7), (0, 0, 5, 9),
    (0, 0, 5, 10), (0, 0, 5, 12), (0, 0, 6, 14), (0, 1, 5, 16),
    (0, 1, 5, 20), (0, 1, 5, 22), (0, 2, 5, 28), (0, 3, 5, 32),
    (0, 4, 5, 48), (32, 6, 5, 64), (0, 7, 5, 128), (0, 8, 6, 256),
    (0, 10, 6, 1024), (0, 12, 6, 4096), (32, 0, 4, 0), (0, 0, 4, 1),
    (0, 0, 5, 2), (32, 0, 5, 4), (0, 0, 5, 5), (32, 0, 5, 7),
    (0, 0, 5, 8), (32, 0, 5, 10), (0, 0, 5, 11), (0, 0, 6, 13),
    (32, 1, 5, 16), (0, 1, 5, 18), (32, 1, 5, 22), (0, 2, 5, 24),
    (32, 3, 5, 32), (0, 3, 5, 40), (0, 6, 4, 64), (16, 6, 4, 64),
    (32, 7, 5, 128), (0, 9, 6, 512), (0, 11, 6, 2048), (48, 0, 4, 0),
    (16, 0, 4, 1), (32, 0, 5, 2), (32, 0, 5, 3), (32, 0, 5, 5),
    (32, 0, 5, 6), (32, 0, 5, 8), (32, 0, 5, 9), (32, 0, 5, 11),
    (32, 0, 5, 12), (0, 0, 6, 15), (32, 1, 5, 18), (32, 1, 5, 20),
    (32, 2, 5, 24), (32, 2, 5, 28), (32, 3, 5, 40), (32, 4, 5, 48),
    (0, 16, 6, 65536), (0, 15, 6, 32768), (0, 14, 6, 16384),
    (0, 13, 6, 8192),
)

_OF_PREDEF: tuple[tuple[int, int, int, int], ...] = (
    (0, 0, 5, 0), (0, 6, 4, 61), (0, 9, 5, 509), (0, 15, 5, 32765),
    (0, 21, 5, 2097149), (0, 3, 5, 5), (0, 7, 4, 125), (0, 12, 5, 4093),
    (0, 18, 5, 262141), (0, 23, 5, 8388605), (0, 5, 5, 29),
    (0, 8, 4, 253), (0, 14, 5, 16381), (0, 20, 5, 1048573), (0, 2, 5, 1),
    (16, 7, 4, 125), (0, 11, 5, 2045), (0, 17, 5, 131069),
    (0, 22, 5, 4194301), (0, 4, 5, 13), (16, 8, 4, 253),
    (0, 13, 5, 8189), (0, 19, 5, 524285), (0, 1, 5, 1), (16, 6, 4, 61),
    (0, 10, 5, 1021), (0, 16, 5, 65533), (0, 28, 5, 268435453),
    (0, 27, 5, 134217725), (0, 26, 5, 67108861), (0, 25, 5, 33554429),
    (0, 24, 5, 16777213),
)

_ML_PREDEF: tuple[tuple[int, int, int, int], ...] = (
    (0, 0, 6, 3), (0, 0, 4, 4), (32, 0, 5, 5), (0, 0, 5, 6),
    (0, 0, 5, 8), (0, 0, 5, 9), (0, 0, 5, 11), (0, 0, 6, 13),
    (0, 0, 6, 16), (0, 0, 6, 19), (0, 0, 6, 22), (0, 0, 6, 25),
    (0, 0, 6, 28), (0, 0, 6, 31), (0, 0, 6, 34), (0, 1, 6, 37),
    (0, 1, 6, 41), (0, 2, 6, 47), (0, 3, 6, 59), (0, 4, 6, 83),
    (0, 7, 6, 131), (0, 9, 6, 515), (16, 0, 4, 4), (0, 0, 4, 5),
    (32, 0, 5, 6), (0, 0, 5, 7), (32, 0, 5, 9), (0, 0, 5, 10),
    (0, 0, 6, 12), (0, 0, 6, 15), (0, 0, 6, 18), (0, 0, 6, 21),
    (0, 0, 6, 24), (0, 0, 6, 27), (0, 0, 6, 30), (0, 0, 6, 33),
    (0, 1, 6, 35), (0, 1, 6, 39), (0, 2, 6, 43), (0, 3, 6, 51),
    (0, 4, 6, 67), (0, 5, 6, 99), (0, 8, 6, 259), (32, 0, 4, 4),
    (48, 0, 4, 4), (16, 0, 4, 5), (32, 0, 5, 7), (32, 0, 5, 8),
    (32, 0, 5, 10), (32, 0, 5, 11), (0, 0, 6, 14), (0, 0, 6, 17),
    (0, 0, 6, 20), (0, 0, 6, 23), (0, 0, 6, 26), (0, 0, 6, 29),
    (0, 0, 6, 32), (0, 16, 6, 65539), (0, 15, 6, 32771),
    (0, 14, 6, 16387), (0, 13, 6, 8195), (0, 12, 6, 4099),
    (0, 11, 6, 2051), (0, 10, 6, 1027),
)

# Per-code add-bits / base-value for sequence symbols.  Used to attach
# the value semantics onto FSE_Compressed-mode tables (where the FSE
# table yields a *code*, not the value directly).
_LL_CODE_BASE = (
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
    16, 18, 20, 22, 24, 28, 32, 40, 48, 64, 128, 256, 512, 1024,
    2048, 4096, 8192, 16384, 32768, 65536,
)
_LL_CODE_BITS = (
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 1, 1, 1, 2, 2, 3, 3, 4, 6, 7, 8, 9, 10, 11, 12,
    13, 14, 15, 16,
)
_ML_CODE_BASE = (
    3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
    19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
    35, 37, 39, 41, 43, 47, 51, 59, 67, 83, 99, 131, 259, 515, 1027,
    2051, 4099, 8195, 16387, 32771, 65539,
)
_ML_CODE_BITS = (
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 1, 1, 1, 2, 2, 3, 3, 4, 4, 5, 7, 8, 9, 10, 11,
    12, 13, 14, 15, 16,
)

# Offset code → base value (zstd ``OF_base``) and additional bits
# (``OF_bits``).  For code N, ``OF_base[N] == (1<<N) - 3`` for N>=2, so
# ``offset = OF_base[N] + readBits(N)`` yields the final offset directly
# when N > 1.  Codes 0/1 are repeat-offset codes resolved against history.
_OF_CODE_BASE = (
    0, 1, 1, 5, 0xD, 0x1D, 0x3D, 0x7D,
    0xFD, 0x1FD, 0x3FD, 0x7FD, 0xFFD, 0x1FFD, 0x3FFD, 0x7FFD,
    0xFFFD, 0x1FFFD, 0x3FFFD, 0x7FFFD, 0xFFFFD, 0x1FFFFD, 0x3FFFFD,
    0x7FFFFD, 0xFFFFFD, 0x1FFFFFD, 0x3FFFFFD, 0x7FFFFFD, 0xFFFFFFD,
    0x1FFFFFFD, 0x3FFFFFFD, 0x7FFFFFFD,
)
_OF_CODE_BITS = tuple(range(32))


class ZstdError(Exception):
    """zstd frame is malformed or uses an unsupported feature."""


# ── Bit readers ──────────────────────────────────────────────────


class _ForwardBitReader:
    """LSB-first forward bit reader for FSE table descriptions.

    zstd's FSE table description is a forward, LSB-first bitstream
    (RFC 8878 §4.1.1).  Supports both consuming reads and a non-consuming
    ``peek`` so the variable-width count decoder can decide how many bits
    it actually used.
    """

    __slots__ = ("_data", "_bitpos")

    def __init__(self, data: bytes) -> None:
        # Big integer with bit 0 = LSB of data[0], so a shift extracts a
        # window starting at any bit position.
        self._data = int.from_bytes(data, "little")
        self._bitpos = 0

    def peek(self, nbits: int) -> int:
        if nbits == 0:
            return 0
        return (self._data >> self._bitpos) & ((1 << nbits) - 1)

    def advance(self, nbits: int) -> None:
        self._bitpos += nbits

    def read(self, nbits: int) -> int:
        val = self.peek(nbits)
        self._bitpos += nbits
        return val


class _BackwardBitReader:
    """Backward bit reader for FSE / Huffman streams (RFC 8878 §4).

    zstd entropy streams are written so the reader starts at the END of
    the byte range, skips the high zero-padding bits up to and including
    the final set "1" sentinel bit, then consumes bits from MSB toward
    the start of the buffer.
    """

    __slots__ = ("_data", "_bitpos")

    def __init__(self, data: bytes) -> None:
        if not data:
            raise ZstdError("empty bitstream")
        # Build a single big integer; bit 0 is the LSB of data[0].
        # We track an absolute bit index and read downward.
        self._data = int.from_bytes(data, "little")
        nbits = len(data) * 8
        # Locate the sentinel: the highest set bit.
        last = data[-1]
        if last == 0:
            raise ZstdError("bitstream final byte is zero (no sentinel)")
        highbit_in_last = last.bit_length() - 1
        # The sentinel is the highest set bit; reading starts just BELOW it.
        self._bitpos = nbits - 8 + highbit_in_last - 1

    def read(self, nbits: int) -> int:
        """Read *nbits* bits (MSB-first within the logical stream)."""
        if nbits == 0:
            return 0
        if self._bitpos < 0:
            # Past the start: zstd treats missing bits as zero.
            return 0
        start = self._bitpos - nbits + 1
        if start < 0:
            # Partial read at the very start; zero-extend the low end.
            avail = self._bitpos + 1
            val = (self._data >> 0) & ((1 << avail) - 1)
            val <<= (nbits - avail)
            self._bitpos -= nbits
            return val
        val = (self._data >> start) & ((1 << nbits) - 1)
        self._bitpos -= nbits
        return val

    def finished(self) -> bool:
        return self._bitpos < 0


class _FseDStreamReader:
    """Faithful port of zstd's ``BIT_DStream`` (64-bit container, MSB-first).

    Used to decode an FSE stream whose symbol count is *not* known ahead of
    time and is therefore determined purely by stream exhaustion — i.e. the
    Huffman weight stream.  Unlike :class:`_BackwardBitReader`, this models
    zstd's exact reload / overflow semantics: the final symbols are decoded
    from the high zero-padding bits of the 8-byte container, and decoding
    stops only when ``bitsConsumed`` exceeds the container width
    (``BIT_DStream_overflow``).  A reader that merely stops at the first
    missing real bit decodes one symbol too few, dropping the last weight.
    """

    _CONT = 8  # container width in bytes (matches zstd's 64-bit register)

    __slots__ = ("_data", "_start", "_ptr", "_container", "_consumed")

    def __init__(self, data: bytes) -> None:
        if not data:
            raise ZstdError("empty bitstream")
        last = data[-1]
        if last == 0:
            raise ZstdError("bitstream final byte is zero (no sentinel)")
        self._data = data
        self._start = 0
        size = len(data)
        skip = 8 - (last.bit_length() - 1)  # padding bits + sentinel
        if size >= self._CONT:
            self._ptr = size - self._CONT
            self._consumed = skip
        else:
            self._ptr = 0
            self._consumed = skip + (self._CONT - size) * 8
        self._container = self._load(self._ptr)

    def _load(self, ptr: int) -> int:
        chunk = self._data[ptr : ptr + self._CONT].ljust(self._CONT, b"\0")
        return int.from_bytes(chunk, "little")

    def read(self, nbits: int) -> int:
        """Read *nbits* bits MSB-first; auto-reloads the container."""
        if nbits == 0:
            return 0
        # zstd masks the shift, so an over-read past the end returns the
        # garbage tail of the container (its result is discarded once the
        # following ``overflowed()`` check breaks the decode loop).
        shift = (self._CONT * 8 - self._consumed - nbits) & (self._CONT * 8 - 1)
        val = (self._container >> shift) & ((1 << nbits) - 1)
        self._consumed += nbits
        self._reload()
        return val

    def _reload(self) -> None:
        if self._consumed > self._CONT * 8 or self._ptr == self._start:
            return
        nbytes = self._consumed >> 3
        if self._ptr - nbytes < self._start:
            nbytes = self._ptr - self._start
        self._ptr -= nbytes
        self._consumed -= nbytes * 8
        self._container = self._load(self._ptr)

    def overflowed(self) -> bool:
        """True once consumed bits exceed the container (BIT_DStream_overflow)."""
        return self._consumed > self._CONT * 8


# ── FSE decoding ─────────────────────────────────────────────────


class _FseTable:
    """A decoded FSE table: per-state symbol, newstate baseline, num_bits."""

    __slots__ = ("accuracy_log", "symbol", "baseline", "num_bits")

    def __init__(
        self,
        accuracy_log: int,
        symbol: list[int],
        baseline: list[int],
        num_bits: list[int],
    ) -> None:
        self.accuracy_log = accuracy_log
        self.symbol = symbol
        self.baseline = baseline
        self.num_bits = num_bits


def _build_fse_table(
    normalized: list[int], accuracy_log: int
) -> _FseTable:
    """Build an FSE decoding table from a normalized count distribution.

    Faithful port of zstd ``FSE_buildDTable_internal`` (the runtime path
    used for FSE_Compressed tables): low-prob (-1) symbols laid at the top,
    positive symbols spread with step ``(size>>1)+(size>>3)+3`` skipping the
    low-prob area, then per-state ``newState`` / ``nbBits`` derived from the
    running symbol occurrence count.  Validated against the vendored C
    decoder's output for ``newState`` and ``nbBits``.
    """
    size = 1 << accuracy_log
    symbol_of_state = [0] * size
    high_threshold = size - 1

    symbol_next = [0] * len(normalized)
    for sym, count in enumerate(normalized):
        if count == -1:
            symbol_of_state[high_threshold] = sym
            high_threshold -= 1
            symbol_next[sym] = 1
        elif count > 0:
            symbol_next[sym] = count

    step = (size >> 1) + (size >> 3) + 3
    mask = size - 1
    pos = 0
    for sym, count in enumerate(normalized):
        if count <= 0:
            continue
        for _ in range(count):
            symbol_of_state[pos] = sym
            pos = (pos + step) & mask
            while pos > high_threshold:
                pos = (pos + step) & mask

    baseline = [0] * size
    num_bits = [0] * size
    for state in range(size):
        sym = symbol_of_state[state]
        nxt = symbol_next[sym]
        symbol_next[sym] += 1
        nb = accuracy_log - (nxt.bit_length() - 1)
        num_bits[state] = nb
        baseline[state] = (nxt << nb) - size

    return _FseTable(accuracy_log, symbol_of_state, baseline, num_bits)


def _read_fse_distribution(
    reader: _ForwardBitReader, max_symbol: int, max_accuracy: int
) -> tuple[list[int], int, int]:
    """Read an FSE table description (RFC 8878 §4.1.1 / zstd FSE_readNCount).

    Returns (normalized_counts, accuracy_log, 0).  The reader is a
    forward LSB-first stream positioned at the start of the description;
    on return its ``_bitpos`` reflects all bits consumed.
    """
    accuracy_log = reader.read(4) + 5
    if accuracy_log > max_accuracy:
        raise ZstdError(
            f"FSE accuracy_log {accuracy_log} exceeds max {max_accuracy}"
        )
    # Faithful port of zstd ``FSE_readNCount_body`` (the LSB-first count
    # bitstream).  ``threshold`` is always a power of two; the count for
    # each symbol reads either ``nbits-1`` bits (low band) or ``nbits``
    # bits (high band).
    remaining = (1 << accuracy_log) + 1
    threshold = 1 << accuracy_log
    nbits = accuracy_log + 1
    counts: list[int] = []
    symbol = 0
    previous_is_zero = False

    while remaining > 1 and symbol <= max_symbol:
        if previous_is_zero:
            # Run of zero-probability symbols: 2-bit repeat fields chain
            # while they read 0b11.
            while True:
                rep = reader.read(2)
                for _ in range(rep):
                    counts.append(0)
                    symbol += 1
                if rep != 3:
                    break
            previous_is_zero = False
            if symbol > max_symbol:
                break
            continue

        max_band = (2 * threshold - 1) - remaining
        peeked = reader.peek(nbits)
        low = peeked & (threshold - 1)
        if low < max_band:
            count = low
            reader.advance(nbits - 1)
        else:
            count = peeked & (2 * threshold - 1)
            if count >= threshold:
                count -= max_band
            reader.advance(nbits)

        count -= 1  # stored value is (proba+1); 0 → proba -1 (prob<1)
        if count >= 0:
            remaining -= count
        else:
            remaining += count  # count == -1
        counts.append(count)
        symbol += 1
        previous_is_zero = count == 0

        if remaining < threshold:
            if remaining <= 1:
                break
            nbits = (remaining).bit_length()  # highbit32(remaining)+1
            threshold = 1 << (nbits - 1)

    if remaining != 1:
        raise ZstdError("FSE distribution did not sum to table size")
    return counts, accuracy_log, 0


# ── Huffman literals decoding ────────────────────────────────────


class _HuffmanTable:
    """Decoded Huffman table: max_bits + per-prefix (symbol, nbits)."""

    __slots__ = ("max_bits", "symbols", "num_bits")

    def __init__(
        self, max_bits: int, symbols: list[int], num_bits: list[int]
    ) -> None:
        self.max_bits = max_bits
        # symbols[code] / num_bits[code] indexed by a max_bits-wide prefix
        self.symbols = symbols
        self.num_bits = num_bits


def _build_huffman_from_weights(weights: list[int]) -> _HuffmanTable:
    """Build a Huffman decode table from per-symbol weights.

    RFC 8878 §4.2.1: a weight ``w`` means bit-length ``max_bits+1-w``
    (weight 0 = symbol absent).  ``max_bits`` is derived from the sum of
    ``2^(w-1)`` over all symbols.
    """
    weight_sum = sum((1 << (w - 1)) for w in weights if w > 0)
    if weight_sum == 0:
        raise ZstdError("empty Huffman weight table")
    max_bits = (weight_sum - 1).bit_length()
    # The last symbol's weight is inferred so the table is complete.
    left = (1 << max_bits) - weight_sum
    if left & (left - 1) != 0 or left == 0:
        raise ZstdError("invalid Huffman weight distribution")
    last_weight = left.bit_length()
    weights = weights + [last_weight]

    table_size = 1 << max_bits
    symbols = [0] * table_size
    num_bits = [0] * table_size

    # Fill the decode table exactly as zstd HUF_readDTableX1: iterate the
    # weights from 1 (longest codes) upward; each symbol of weight w gets
    # ``2^(w-1)`` consecutive table entries with ``nbBits = max_bits+1-w``.
    # Within a weight, symbols are taken in symbol-value order.  This puts
    # the longest codes at the low table indices, matching the MSB-first
    # prefix lookup.
    pos = 0
    for w in range(1, max_bits + 1):
        nb = max_bits + 1 - w
        span = 1 << (w - 1)
        for sym, sym_weight in enumerate(weights):
            if sym_weight == w:
                for _ in range(span):
                    symbols[pos] = sym
                    num_bits[pos] = nb
                    pos += 1
    if pos != table_size:
        raise ZstdError("Huffman table not fully populated")
    return _HuffmanTable(max_bits, symbols, num_bits)


def _decode_huffman_weights(
    src: bytes, header_byte: int
) -> tuple[list[int], int]:
    """Decode the Huffman weight description.

    Returns (weights, bytes_consumed_including_header_byte).
    ``header_byte`` is the first byte of the Huffman tree description.
    """
    if header_byte >= 128:
        # Direct representation: (header_byte - 127) weights, 4 bits each.
        num_weights = header_byte - 127
        nbytes = (num_weights + 1) // 2
        weights: list[int] = []
        for i in range(nbytes):
            b = src[1 + i]
            weights.append(b >> 4)
            if len(weights) < num_weights:
                weights.append(b & 0xF)
        return weights[:num_weights], 1 + nbytes

    # FSE-compressed weights.  header_byte = compressed size in bytes.
    comp_size = header_byte
    fse_bytes = src[1 : 1 + comp_size]
    if len(fse_bytes) < comp_size:
        raise ZstdError("truncated Huffman FSE weights")
    weights = _fse_decode_weight_stream(fse_bytes)
    return weights, 1 + comp_size


def _fse_decode_weight_stream(fse_bytes: bytes) -> list[int]:
    """Decode the FSE-compressed Huffman weight bitstream.

    The weights use a max symbol value of 255 and accuracy_log ≤ 6.  Two
    interleaved FSE states alternate, decoding from a single backward
    bitstream (RFC 8878 §4.2.1.2).
    """
    fwd = _ForwardBitReader(fse_bytes)
    counts, accuracy_log, _ = _read_fse_distribution(
        fwd, max_symbol=255, max_accuracy=6
    )
    # Bytes consumed by the table description, rounded up.
    table_bits = fwd._bitpos
    table_bytes = (table_bits + 7) // 8
    table = _build_fse_table(counts, accuracy_log)

    stream = fse_bytes[table_bytes:]
    br = _FseDStreamReader(stream)

    state1 = br.read(accuracy_log)
    state2 = br.read(accuracy_log)

    # Faithful port of zstd ``FSE_decompress_usingDTable_generic`` tail
    # drain.  Each step emits the state's current symbol and then advances
    # the state by reading its transition bits (``FSE_decodeSymbol``);
    # exhaustion (``BIT_DStream_overflow``) is tested *after* that read.
    # The two interleaved states are drained until one read overflows.  This
    # exact ordering matters: a flat backward reader that stops the instant
    # it runs out of real bits drops the final weight on certain byte
    # boundaries, corrupting the Huffman table for single-stream literals.
    sym, base, nbits = table.symbol, table.baseline, table.num_bits
    weights: list[int] = []

    while True:
        weights.append(sym[state1])
        state1 = base[state1] + br.read(nbits[state1])
        if br.overflowed():
            weights.append(sym[state2])
            break
        weights.append(sym[state2])
        state2 = base[state2] + br.read(nbits[state2])
        if br.overflowed():
            weights.append(sym[state1])
            break
    return weights


def _decode_literals_huffman(
    table: _HuffmanTable, stream: bytes, out_size: int
) -> bytes:
    """Decode ``out_size`` symbols from a single Huffman backward stream."""
    br = _BackwardBitReader(stream)
    out = bytearray()
    max_bits = table.max_bits
    for _ in range(out_size):
        prefix = br.read(max_bits)
        sym = table.symbols[prefix]
        nb = table.num_bits[prefix]
        out.append(sym)
        # We over-read max_bits; rewind by (max_bits - nb).
        br._bitpos += (max_bits - nb)
    return bytes(out)


# ── Literals section ─────────────────────────────────────────────


def _decode_literals(
    src: bytes, prev_huffman: _HuffmanTable | None
) -> tuple[bytes, int, _HuffmanTable | None]:
    """Decode a block's Literals_Section.

    Returns (literals, bytes_consumed, huffman_table_for_reuse).
    """
    b0 = src[0]
    block_type = b0 & 0x3
    size_format = (b0 >> 2) & 0x3

    if block_type == 0 or block_type == 1:
        # Raw (0) or RLE (1) literals.
        if size_format == 0 or size_format == 2:
            regen = b0 >> 3
            hdr = 1
        elif size_format == 1:
            regen = (b0 >> 4) | (src[1] << 4)
            hdr = 2
        else:
            regen = (b0 >> 4) | (src[1] << 4) | (src[2] << 12)
            hdr = 3
        if block_type == 0:
            lits = src[hdr : hdr + regen]
            if len(lits) < regen:
                raise ZstdError("truncated raw literals")
            return bytes(lits), hdr + regen, prev_huffman
        # RLE: one byte repeated.
        return bytes([src[hdr]]) * regen, hdr + 1, prev_huffman

    # Compressed (2) or Treeless (3) literals.
    if size_format == 0 or size_format == 1:
        regen = (b0 >> 4) | ((src[1] & 0x3F) << 4)
        comp = (src[1] >> 6) | (src[2] << 2)
        hdr = 3
        num_streams = 1 if size_format == 0 else 4
    elif size_format == 2:
        regen = (b0 >> 4) | (src[1] << 4) | ((src[2] & 0x3) << 12)
        comp = (src[2] >> 2) | (src[3] << 6)
        hdr = 4
        num_streams = 4
    else:
        regen = (b0 >> 4) | (src[1] << 4) | ((src[2] & 0x3F) << 12)
        comp = (src[2] >> 6) | (src[3] << 2) | (src[4] << 10)
        hdr = 5
        num_streams = 4

    payload = src[hdr : hdr + comp]
    if len(payload) < comp:
        raise ZstdError("truncated compressed literals")

    if block_type == 2:
        # New Huffman tree precedes the stream(s).
        weights, tree_bytes = _decode_huffman_weights(payload, payload[0])
        table = _build_huffman_from_weights(weights)
        stream_data = payload[tree_bytes:]
    else:
        # Treeless: reuse the previous block's table.
        if prev_huffman is None:
            raise ZstdError("treeless literals with no prior Huffman table")
        table = prev_huffman
        stream_data = payload

    if num_streams == 1:
        lits = _decode_literals_huffman(table, stream_data, regen)
    else:
        lits = _decode_literals_4streams(table, stream_data, regen)

    return lits, hdr + comp, table


def _decode_literals_4streams(
    table: _HuffmanTable, data: bytes, regen: int
) -> bytes:
    """Decode the 4-stream Huffman literals layout (RFC 8878 §4.2.2)."""
    if len(data) < 6:
        raise ZstdError("truncated 4-stream literals jump table")
    s1 = int.from_bytes(data[0:2], "little")
    s2 = int.from_bytes(data[2:4], "little")
    s3 = int.from_bytes(data[4:6], "little")
    streams_start = 6
    total = len(data) - streams_start
    s4 = total - (s1 + s2 + s3)
    if s4 < 0:
        raise ZstdError("invalid 4-stream literals sizes")

    sizes = [s1, s2, s3, s4]
    # First three streams each emit ceil(regen/4) symbols; the 4th gets
    # the remainder.
    seg = (regen + 3) // 4
    out_sizes = [seg, seg, seg, regen - 3 * seg]

    out = bytearray()
    off = streams_start
    for i in range(4):
        chunk = data[off : off + sizes[i]]
        off += sizes[i]
        out += _decode_literals_huffman(table, chunk, out_sizes[i])
    return bytes(out)


# ── Sequences section ────────────────────────────────────────────


class _SeqDTable:
    """An FSE table over sequence symbols (LL / OF / ML).

    Each state carries the decoded value semantics directly:
      * ``base_value`` — for LL/ML the literals/match-length base; for OF
        the offset code (the value computed as ``(1<<code) + addbits``).
      * ``add_bits``   — number of extra bits to read for this symbol.
      * ``newstate``   — newState baseline for the FSE state transition.
      * ``state_nbits``— bits to read for the FSE state transition.
    """

    __slots__ = ("accuracy_log", "base_value", "add_bits",
                 "newstate", "state_nbits", "is_offset")

    def __init__(
        self,
        accuracy_log: int,
        base_value: list[int],
        add_bits: list[int],
        newstate: list[int],
        state_nbits: list[int],
        is_offset: bool,
    ) -> None:
        self.accuracy_log = accuracy_log
        self.base_value = base_value
        self.add_bits = add_bits
        self.newstate = newstate
        self.state_nbits = state_nbits
        self.is_offset = is_offset


# (predefined_dtable, code_base, code_bits, max_symbol, is_offset) per key.
_SeqSpec = tuple[
    tuple[tuple[int, int, int, int], ...],
    tuple[int, ...] | None,
    tuple[int, ...] | None,
    int,
    bool,
]
_SEQ_SPEC: dict[str, _SeqSpec] = {
    "ll": (_LL_PREDEF, _LL_CODE_BASE, _LL_CODE_BITS, 35, False),
    "of": (_OF_PREDEF, None, None, 31, True),
    "ml": (_ML_PREDEF, _ML_CODE_BASE, _ML_CODE_BITS, 52, False),
}


def _decode_sequences(
    src: bytes,
    prev_tables: dict[str, _SeqDTable | None],
    repeat_offsets: list[int],
) -> tuple[list[tuple[int, int, int]], int]:
    """Decode the Sequences_Section.

    Returns (sequences, bytes_consumed) where each sequence is
    ``(literal_length, final_offset, match_length)`` — the offset is fully
    resolved (repeat-offset history applied).  ``prev_tables`` and
    ``repeat_offsets`` are mutated in place to carry state across blocks.
    """
    pos = 0
    b0 = src[pos]
    pos += 1
    if b0 == 0:
        return [], pos
    if b0 < 128:
        num_seq = b0
    elif b0 < 255:
        num_seq = ((b0 - 128) << 8) + src[pos]
        pos += 1
    else:
        num_seq = src[pos] + (src[pos + 1] << 8) + 0x7F00
        pos += 2

    compression_modes = src[pos]
    pos += 1
    ll_mode = (compression_modes >> 6) & 0x3
    of_mode = (compression_modes >> 4) & 0x3
    ml_mode = (compression_modes >> 2) & 0x3

    # Each FSE table description (or RLE byte) is byte-aligned: zstd reads
    # each from a fresh, byte-aligned position and rounds the consumed bit
    # count up to whole bytes before the next.
    ll_table, used = _resolve_seq_table(src, pos, ll_mode, prev_tables, "ll")
    pos += used
    of_table, used = _resolve_seq_table(src, pos, of_mode, prev_tables, "of")
    pos += used
    ml_table, used = _resolve_seq_table(src, pos, ml_mode, prev_tables, "ml")
    pos += used

    bitstream = src[pos:]
    br = _BackwardBitReader(bitstream)

    ll_state = br.read(ll_table.accuracy_log)
    of_state = br.read(of_table.accuracy_log)
    ml_state = br.read(ml_table.accuracy_log)

    sequences: list[tuple[int, int, int]] = []
    rep = repeat_offsets
    for i in range(num_seq):
        # Resolve offset, then match length, then literals length — the
        # exact read order and repeat-offset logic of zstd
        # ZSTD_decodeSequence (RFC 8878 §3.1.1.4 / §4.2.3).
        of_base = of_table.base_value[of_state]
        of_bits = of_table.add_bits[of_state]
        ll_base = ll_table.base_value[ll_state]

        if of_bits > 1:
            offset = of_base + br.read(of_bits)
            rep[2] = rep[1]
            rep[1] = rep[0]
            rep[0] = offset
        else:
            ll0 = 1 if ll_base == 0 else 0
            if of_bits == 0:
                offset = _resolve_rep0(rep, ll0)
            else:
                code = of_base + ll0 + br.read(1)
                offset = _resolve_rep_code(rep, code)

        ml = ml_table.base_value[ml_state] + br.read(ml_table.add_bits[ml_state])
        ll = ll_base + br.read(ll_table.add_bits[ll_state])

        sequences.append((ll, offset, ml))

        if i == num_seq - 1:
            break
        # State updates: LL, ML, then OF (order per RFC 8878 §4.2.3).
        ll_state = ll_table.newstate[ll_state] + br.read(
            ll_table.state_nbits[ll_state]
        )
        ml_state = ml_table.newstate[ml_state] + br.read(
            ml_table.state_nbits[ml_state]
        )
        of_state = of_table.newstate[of_state] + br.read(
            of_table.state_nbits[of_state]
        )

    return sequences, pos + len(bitstream)


def _resolve_rep0(rep: list[int], ll0: int) -> int:
    """Resolve an ofBits==0 (pure repeat) offset and update history.

    Mirrors zstd: ``offset = prevOffset[ll0];
    prevOffset[1] = prevOffset[!ll0]; prevOffset[0] = offset``.
    """
    offset = rep[ll0]
    other = rep[1 - ll0]
    rep[1] = other
    rep[0] = offset
    return offset


def _resolve_rep_code(rep: list[int], code: int) -> int:
    """Resolve an ofBits==1 repeat-code offset and update history.

    Mirrors zstd: ``temp = (code==3) ? prevOffset[0]-1 : prevOffset[code];
    if (code!=1) prevOffset[2]=prevOffset[1];
    prevOffset[1]=prevOffset[0]; prevOffset[0]=temp``.
    """
    temp = rep[0] - 1 if code == 3 else rep[code]
    if temp == 0:
        # 0 is invalid — zstd forces -1 to surface corruption downstream.
        raise ZstdError("invalid repeat offset (resolved to 0)")
    if code != 1:
        rep[2] = rep[1]
    rep[1] = rep[0]
    rep[0] = temp
    return temp


def _resolve_seq_table(
    src: bytes,
    pos: int,
    mode: int,
    prev_tables: dict[str, _SeqDTable | None],
    key: str,
) -> tuple[_SeqDTable, int]:
    """Resolve one sequence FSE table per its mode.

    Returns ``(table, bytes_used)``.  Each table description (or RLE byte)
    is byte-aligned at *pos* — zstd reads each from a fresh, byte-aligned
    position and rounds up to whole bytes before the next.
    """
    predef, code_base, code_bits, max_symbol, is_offset = _SEQ_SPEC[key]

    if mode == 0:
        # Predefined: use the vendored zstd pre-spread DTable verbatim.
        size = len(predef)
        accuracy_log = (size - 1).bit_length()
        base_value = [row[3] for row in predef]
        add_bits = [row[1] for row in predef]
        newstate = [row[0] for row in predef]
        state_nbits = [row[2] for row in predef]
        table = _SeqDTable(
            accuracy_log, base_value, add_bits, newstate, state_nbits,
            is_offset,
        )
        used = 0
    elif mode == 1:
        # RLE: a single symbol byte with accuracy_log 0.
        code = src[pos]
        if is_offset:
            base_value = [_OF_CODE_BASE[code]]
            add_bits = [_OF_CODE_BITS[code]]
        else:
            assert code_base is not None and code_bits is not None
            base_value = [code_base[code]]
            add_bits = [code_bits[code]]
        table = _SeqDTable(0, base_value, add_bits, [0], [0], is_offset)
        used = 1
    elif mode == 2:
        # FSE_Compressed: read a byte-aligned table description, then
        # attach value semantics to each state's symbol (code).
        max_acc = 8 if is_offset else 9
        fwd = _ForwardBitReader(src[pos:])
        counts, accuracy_log, _ = _read_fse_distribution(
            fwd, max_symbol=max_symbol, max_accuracy=max_acc
        )
        used = (fwd._bitpos + 7) // 8
        fse = _build_fse_table(counts, accuracy_log)
        if is_offset:
            base_value = [_OF_CODE_BASE[c] for c in fse.symbol]
            add_bits = [_OF_CODE_BITS[c] for c in fse.symbol]
        else:
            assert code_base is not None and code_bits is not None
            base_value = [code_base[c] for c in fse.symbol]
            add_bits = [code_bits[c] for c in fse.symbol]
        table = _SeqDTable(
            accuracy_log, base_value, add_bits,
            fse.baseline, fse.num_bits, is_offset,
        )
    else:
        # Repeat: reuse the previous table.
        prev = prev_tables.get(key)
        if prev is None:
            raise ZstdError(f"repeat mode for {key} table with no prior table")
        table = prev
        used = 0
    prev_tables[key] = table
    return table, used


# ── Sequence execution ───────────────────────────────────────────


def _execute_sequences(
    literals: bytes,
    sequences: list[tuple[int, int, int]],
    out: bytearray,
) -> None:
    """Apply decoded sequences to produce output (RFC 8878 §3.1.1.4).

    Offsets in *sequences* are already fully resolved (the repeat-offset
    history was applied in ``_decode_sequences``), so this step only
    copies literals and matches.
    """
    lit_pos = 0
    for ll, offset, ml in sequences:
        # Copy literals.
        if ll:
            out += literals[lit_pos : lit_pos + ll]
            lit_pos += ll

        # Copy match (may overlap with just-written output).
        if ml:
            start = len(out) - offset
            if start < 0:
                raise ZstdError("match offset before start of output")
            for j in range(ml):
                out.append(out[start + j])

    # Trailing literals after the last sequence.
    if lit_pos < len(literals):
        out += literals[lit_pos:]


# ── Block / frame decoding ───────────────────────────────────────


def _decompress_frame(data: bytes) -> bytes:
    """Decompress one zstd frame; return the plaintext."""
    if len(data) < 5:
        raise ZstdError("input too short for a zstd frame")
    magic = int.from_bytes(data[0:4], "little")
    if magic != _MAGIC:
        raise ZstdError(f"bad zstd magic 0x{magic:08x}")

    pos = 4
    fhd = data[pos]
    pos += 1
    dict_id_flag = fhd & 0x3
    content_checksum = (fhd >> 2) & 1
    single_segment = (fhd >> 5) & 1
    fcs_flag = (fhd >> 6) & 0x3

    if not single_segment:
        # Window descriptor byte (we don't enforce window size).
        pos += 1

    if dict_id_flag:
        dict_id_size = {1: 1, 2: 2, 3: 4}[dict_id_flag]
        dict_id = int.from_bytes(data[pos : pos + dict_id_size], "little")
        pos += dict_id_size
        if dict_id != 0:
            raise ZstdError(
                "dictionary-compressed frames are not supported "
                "(restic/rustic does not use dictionaries)"
            )

    fcs_size = {0: (1 if single_segment else 0), 1: 2, 2: 4, 3: 8}[fcs_flag]
    if fcs_size:
        _ = int.from_bytes(data[pos : pos + fcs_size], "little")
        pos += fcs_size

    out = bytearray()
    prev_huffman: _HuffmanTable | None = None
    prev_seq_tables: dict[str, _SeqDTable | None] = {
        "ll": None, "of": None, "ml": None
    }
    repeat_offsets = [1, 4, 8]

    while True:
        if pos + 3 > len(data):
            raise ZstdError("truncated block header")
        bh = data[pos] | (data[pos + 1] << 8) | (data[pos + 2] << 16)
        pos += 3
        last_block = bh & 1
        block_type = (bh >> 1) & 0x3
        block_size = bh >> 3

        if block_type == 0:
            # Raw block.
            out += data[pos : pos + block_size]
            pos += block_size
        elif block_type == 1:
            # RLE block: one byte repeated block_size times.
            out += bytes([data[pos]]) * block_size
            pos += 1
        elif block_type == 2:
            block = data[pos : pos + block_size]
            if len(block) < block_size:
                raise ZstdError("truncated compressed block")
            pos += block_size
            lits, lit_consumed, prev_huffman = _decode_literals(
                block, prev_huffman
            )
            seqs, _ = _decode_sequences(
                block[lit_consumed:], prev_seq_tables, repeat_offsets
            )
            _execute_sequences(lits, seqs, out)
        else:
            raise ZstdError("reserved block type 3")

        if last_block:
            break

    if content_checksum:
        # 4-byte truncated XXH64 of the content.
        if pos + 4 > len(data):
            raise ZstdError("missing content checksum")
        want = int.from_bytes(data[pos : pos + 4], "little")
        pos += 4
        got = _xxh64(bytes(out), 0) & 0xFFFFFFFF
        if got != want:
            raise ZstdError("content checksum mismatch")

    return bytes(out)


# ── XXH64 (for the optional content checksum) ─────────────────────

_P64_1 = 0x9E3779B185EBCA87
_P64_2 = 0xC2B2AE3D27D4EB4F
_P64_3 = 0x165667B19E3779F9
_P64_4 = 0x85EBCA77C2B2AE63
_P64_5 = 0x27D4EB2F165667C5
_MASK64 = 0xFFFFFFFFFFFFFFFF


def _rotl64(x: int, r: int) -> int:
    return ((x << r) | (x >> (64 - r))) & _MASK64


def _xxh64(data: bytes, seed: int) -> int:
    """Compute XXH64 (used for the zstd frame content checksum)."""
    length = len(data)
    idx = 0
    if length >= 32:
        v1 = (seed + _P64_1 + _P64_2) & _MASK64
        v2 = (seed + _P64_2) & _MASK64
        v3 = seed & _MASK64
        v4 = (seed - _P64_1) & _MASK64
        while idx + 32 <= length:
            v1 = _xxh64_round(v1, _read64(data, idx))
            v2 = _xxh64_round(v2, _read64(data, idx + 8))
            v3 = _xxh64_round(v3, _read64(data, idx + 16))
            v4 = _xxh64_round(v4, _read64(data, idx + 24))
            idx += 32
        h64 = (
            _rotl64(v1, 1) + _rotl64(v2, 7)
            + _rotl64(v3, 12) + _rotl64(v4, 18)
        ) & _MASK64
        h64 = _xxh64_merge(h64, v1)
        h64 = _xxh64_merge(h64, v2)
        h64 = _xxh64_merge(h64, v3)
        h64 = _xxh64_merge(h64, v4)
    else:
        h64 = (seed + _P64_5) & _MASK64

    h64 = (h64 + length) & _MASK64

    while idx + 8 <= length:
        k1 = _xxh64_round(0, _read64(data, idx))
        h64 ^= k1
        h64 = (_rotl64(h64, 27) * _P64_1 + _P64_4) & _MASK64
        idx += 8
    if idx + 4 <= length:
        h64 ^= (_read32(data, idx) * _P64_1) & _MASK64
        h64 = (_rotl64(h64, 23) * _P64_2 + _P64_3) & _MASK64
        idx += 4
    while idx < length:
        h64 ^= (data[idx] * _P64_5) & _MASK64
        h64 = (_rotl64(h64, 11) * _P64_1) & _MASK64
        idx += 1

    h64 ^= h64 >> 33
    h64 = (h64 * _P64_2) & _MASK64
    h64 ^= h64 >> 29
    h64 = (h64 * _P64_3) & _MASK64
    h64 ^= h64 >> 32
    return h64 & _MASK64


def _xxh64_round(acc: int, inp: int) -> int:
    acc = (acc + (inp * _P64_2)) & _MASK64
    acc = _rotl64(acc, 31)
    acc = (acc * _P64_1) & _MASK64
    return acc


def _xxh64_merge(acc: int, val: int) -> int:
    val = _xxh64_round(0, val)
    acc ^= val
    acc = (acc * _P64_1 + _P64_4) & _MASK64
    return acc


def _read64(data: bytes, off: int) -> int:
    value: int = struct.unpack_from("<Q", data, off)[0]
    return value


def _read32(data: bytes, off: int) -> int:
    value: int = struct.unpack_from("<I", data, off)[0]
    return value


# ── Public API ───────────────────────────────────────────────────


def decompress(data: bytes, max_output_size: int = 0) -> bytes:
    """Decompress a single zstd frame.

    Args:
        data: A complete zstd frame (magic ``0x28 0xB5 0x2F 0xFD`` …).
        max_output_size: Optional sanity cap on the decompressed size; a
            frame whose output would exceed this raises ``ZstdError``.
            ``0`` (default) means no cap.

    Returns:
        The decompressed bytes.

    Raises:
        ZstdError: malformed frame, unsupported feature (dictionaries),
            or output exceeding *max_output_size*.
    """
    result = _decompress_frame(data)
    if max_output_size and len(result) > max_output_size:
        raise ZstdError(
            f"decompressed size {len(result)} exceeds cap {max_output_size}"
        )
    return result
