/*
 * test_repo.c -- exercise repo.c against a real encrypted fixture.
 *
 * Uses recovery/tests/fixtures/repo (generated by gen_fixture.py) to
 * test the full restic-format decryption pipeline:
 *
 *   - lcsas_repo_load_key_file          (scrypt + AES-CTR + Poly1305)
 *   - lcsas_repo_load_keys_dir          (scan keys/)
 *   - lcsas_repo_decrypt                (direct AEAD)
 *   - lcsas_repo_load_index             (parse index JSON, find blobs)
 *   - lcsas_repo_load_snapshots         (parse snapshot list)
 *   - lcsas_snapshot_latest / _find     (snapshot lookups)
 *   - lcsas_blob_index_find             (blob lookups)
 *
 * The fixture's expected blob IDs are read from manifest.json and
 * pinned in this test.
 */
#include "repo.h"
#include "tree.h"
#include "hex.h"
#include "json_q.h"
#include "lcsas_io.h"
#include "aes.h"
#include "poly1305.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <sys/stat.h>
#include <unistd.h>

static int fails = 0;

/* Fixture-pinned values (regenerate gen_fixture.py changes these). */
#define FIXTURE_PASSWORD       "test"
#define FIXTURE_DATA_BLOB_HEX  \
    "6565160e5ca15054fd190b02fab20e4e7daf41e54d19e649d0798d7aca56c5b2"
#define FIXTURE_TREE_BLOB_HEX  \
    "68255a117162e193d9a8e4940756c5754b20eb2e9f6e8934d68b31bcd0f5aa20"
#define FIXTURE_PACK_HEX       \
    "303294d19875abfad5ac347ac2f0a586936efd2850b7252378cafac5c4bd3ec6"
/* RST-02: a data blob stored UNcompressed whose plaintext is itself a
 * zstd frame; index entry has no uncompressed_length.  read_blob must
 * return it verbatim (no false decompression). */
#define FIXTURE_ZMAGIC_BLOB_HEX \
    "1ced7ffcc1a7d50543ef724a3c7e4bef5504e5c51d0e76bfd0b8217222e60b35"
#define FIXTURE_XATTR_BLOB_HEX \
    "c8bc50e94a5aad4482a505268c3616656540113d62050921d6d7778c16d8eadb"
#define FIXTURE_HLINK_BLOB_HEX \
    "b12cdb5f098ad21783e8973d5d864e90c13b7cceedcfcf8013d94d8f7bd05247"
#define FIXTURE_BROKEN_TREE_HEX  \
    "b9a34a1fa85b4ccdcd91b96abdb97acd76c914ba1f99c0f9c61e08842861add3"
#define FIXTURE_BAD_HEX_TREE_HEX \
    "e9b21400fad094fe6f80db621ec8e68ace890c09875e807db12e9e78d65c884a"
#define FIXTURE_BAD_SUBDIR_TREE_HEX \
    "8d615e95dd9cd90bb4a14ee546624b8230280e4b31597c28fff105d7e8eb12f1"
#define FIXTURE_WRONG_NODES_TREE_HEX \
    "220de5d552d29def627b3351c74dba144aa87d059d481224bb1eb753f6d342ac"
#define FIXTURE_LONG_NAME_TREE_HEX \
    "95094ebdf69956bc13345d8204a1263f1f11a04c2237783ce640da2763f698a6"
#define FIXTURE_LONG_TYPE_TREE_HEX \
    "1ae33da29ce6b897a97828272948ec450f1aa93e721365c5ceae9bf6f2e82dc0"
#define FIXTURE_MISSING_CONTENT_TREE_HEX \
    "2c36600359aa0ab187e85c582a93fa2710a1a42516dc12c0110c3ac88e9f9cbe"
/* Fictional tree blob whose pack file does not exist on disk. */
#define FIXTURE_MISSING_TREE_HEX \
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
/* T1C-03: tree with a legitimate "evil" file plus a hostile "evil\0x"
 * whose name carries a JSON ` ` escape (literal NUL).  Both map to
 * basename "evil" under C-string truncation; the hostile node must be
 * skipped so the sibling's content survives intact. */
#define FIXTURE_NUL_NAME_TREE_HEX \
    "39b129393d23aac68106bff79a945674dd27f077f6e02234a7c91677750fb9a9"
/* Content of the legitimate "evil" sibling (== nulsib_plain). */
#define FIXTURE_NUL_SIBLING_CONTENT "the real sibling content\n"

/* Locate the fixture directory.  Honour LCSAS_TEST_FIXTURE_DIR for
 * out-of-tree builds; otherwise assume cwd is repo root or recovery/. */
static const char *fixture_path(char *buf, size_t cap)
{
    const char *override = getenv("LCSAS_TEST_FIXTURE_DIR");
    if (override) {
        snprintf(buf, cap, "%s", override);
        return buf;
    }
    snprintf(buf, cap, "recovery/tests/fixtures/repo");
    if (access(buf, F_OK) == 0) return buf;
    snprintf(buf, cap, "tests/fixtures/repo");
    return buf;
}

/* ---- T1C-05 helpers: craft encrypted index files on the fly ----------
 *
 * decrypt_repo_file is static, so the only way to exercise its
 * reason-code paths through lcsas_repo_load_index is to feed it real
 * MAC-valid encrypted files.  These helpers mirror the Python
 * gen_fixture.py encrypt_authenticated() (AES-256-CTR + Poly1305-AES,
 * output IV(16) || ciphertext || MAC(16)) using the loaded master key. */

/* Encrypt `plain` under `mk` with `iv` and write IV||ct||tag to `path`.
 * Returns 0 on success. */
static int
enc_write(const lcsas_master_key *mk, const unsigned char iv[16],
          const unsigned char *plain, size_t plen, const char *path)
{
    lcsas_aes256_key ek;
    lcsas_aes128_key sk;
    unsigned char *file = NULL;
    unsigned char s[16];
    FILE *f;
    size_t total = 16 + plen + 16;

    file = (unsigned char *)malloc(total);
    if (!file) return -1;
    memcpy(file, iv, 16);
    lcsas_aes256_set_key(&ek, mk->encrypt);
    lcsas_aes256_ctr(&ek, iv, plain, file + 16, plen);
    /* s = AES-128-ECB(mac_k, iv); tag = Poly1305(mac_r, s, ciphertext). */
    lcsas_aes128_set_key(&sk, mk->mac_k);
    lcsas_aes128_encrypt(&sk, iv, s);
    lcsas_poly1305_mac(mk->mac_r, s, file + 16, plen, file + 16 + plen);

    f = fopen(path, "wb");
    if (!f) { free(file); return -1; }
    if (fwrite(file, 1, total, f) != total) { fclose(f); free(file); return -1; }
    fclose(f);
    free(file);
    return 0;
}

/* Copy every regular file in <fixture>/index into <dst>/index, creating
 * <dst>/index.  Returns 0 on success.  Used so the crafted-bad-file
 * cases load against a directory that ALSO contains the genuine,
 * fully-loadable index files. */
static int
copy_valid_indexes(const char *fixture_repo, const char *dst_repo)
{
    char src_dir[1024], dst_dir[1024], src[2048], dst[2048];
    DIR *d;
    struct dirent *e;

    snprintf(dst_dir, sizeof dst_dir, "%s/index", dst_repo);
    if (mkdir(dst_repo, 0700) != 0 && access(dst_repo, F_OK) != 0) return -1;
    if (mkdir(dst_dir, 0700) != 0 && access(dst_dir, F_OK) != 0) return -1;

    snprintf(src_dir, sizeof src_dir, "%s/index", fixture_repo);
    d = opendir(src_dir);
    if (!d) return -1;
    while ((e = readdir(d)) != NULL) {
        unsigned char *buf = NULL;
        size_t n = 0;
        FILE *out;
        if (e->d_name[0] == '.') continue;
        snprintf(src, sizeof src, "%s/%s", src_dir, e->d_name);
        snprintf(dst, sizeof dst, "%s/%s", dst_dir, e->d_name);
        if (lcsas_read_file(src, &buf, &n) != 0) { closedir(d); return -1; }
        out = fopen(dst, "wb");
        if (!out) { free(buf); closedir(d); return -1; }
        if (fwrite(buf, 1, n, out) != n) {
            fclose(out); free(buf); closedir(d); return -1;
        }
        fclose(out);
        free(buf);
    }
    closedir(d);
    return 0;
}

int
main(void)
{
    char repo_buf[1024];
    char path[1024];
    const char *repo;
    lcsas_master_key mk;
    int rc;
    unsigned char data_id[32], tree_id[32];

    repo = fixture_path(repo_buf, sizeof repo_buf);
    fprintf(stderr, "[test_repo] using fixture: %s\n", repo);

    /* ── lcsas_repo_load_keys_dir: scan keys/ and decrypt with password ── */
    snprintf(path, sizeof path, "%s/keys", repo);
    rc = lcsas_repo_load_keys_dir(
        path, (const unsigned char *)FIXTURE_PASSWORD,
        strlen(FIXTURE_PASSWORD), &mk
    );
    if (rc != 0) {
        fprintf(stderr, "FAIL: load_keys_dir rc=%d\n", rc);
        return 1;
    }

    /* Master key should match the fixture's pinned bytes. */
    {
        size_t i;
        unsigned char expected_enc[32];
        for (i = 0; i < 32; i++) expected_enc[i] = (unsigned char)i;
        if (memcmp(mk.encrypt, expected_enc, 32) != 0) {
            fprintf(stderr, "FAIL: master key encrypt bytes mismatch\n");
            fails++;
        }
    }

    /* ── Wrong password must fail with the DISTINCT reject code ────── */
    {
        lcsas_master_key bad;
        rc = lcsas_repo_load_keys_dir(
            path, (const unsigned char *)"wrong-password", 14, &bad
        );
        /* A real key file positively MAC-rejects the password -> the
         * terminal wrong-password code (mapped to exit 77 by main.c,
         * #384).  NOT the generic -1 that a setup failure returns. */
        if (rc != LCSAS_REPO_ERR_WRONG_PASSWORD) {
            fprintf(stderr,
                    "FAIL: wrong password rc=%d, want %d (WRONG_PASSWORD)\n",
                    rc, LCSAS_REPO_ERR_WRONG_PASSWORD);
            fails++;
        }
    }

    /* ── Nonexistent keys dir is NOT a password verdict ────────────── */
    {
        lcsas_master_key bad;
        rc = lcsas_repo_load_keys_dir(
            "/tmp/does-not-exist-keys",
            (const unsigned char *)FIXTURE_PASSWORD,
            strlen(FIXTURE_PASSWORD), &bad
        );
        /* Must be the generic -1, never WRONG_PASSWORD: the password was
         * never tested, so the cascade must stay free to try other
         * tiers (#384 round 2). */
        if (rc != -1) {
            fprintf(stderr,
                    "FAIL: nonexistent keys dir rc=%d, want -1 (generic)\n",
                    rc);
            fails++;
        }
    }

    /* ── lcsas_repo_load_key_file directly ─────────────────────────── */
    {
        /* The keys/ dir has multiple files (stubs + the real key).
         * Walk the directory and find ONE that decrypts.  This also
         * implicitly exercises stub key files that fail MAC verification. */
        lcsas_master_key direct;
        char keyfile[1024];
        DIR *d;
        struct dirent *e;
        int found_real = 0;
        snprintf(keyfile, sizeof keyfile, "%s/keys", repo);
        d = opendir(keyfile);
        if (d) {
            while ((e = readdir(d))) {
                if (e->d_name[0] == '.') continue;
                snprintf(keyfile, sizeof keyfile, "%s/keys/%s",
                         repo, e->d_name);
                if (lcsas_repo_load_key_file(
                        keyfile, (const unsigned char *)FIXTURE_PASSWORD,
                        strlen(FIXTURE_PASSWORD), &direct) == 0) {
                    if (memcmp(direct.encrypt, mk.encrypt, 32) != 0) {
                        fprintf(stderr,
                                "FAIL: direct load_key_file mismatch\n");
                        fails++;
                    }
                    found_real = 1;
                    break;
                }
            }
            closedir(d);
        }
        if (!found_real) {
            fprintf(stderr, "FAIL: no key file in dir decrypted\n");
            fails++;
        }
    }

    /* ── lcsas_repo_load_key_file on garbage file ──────────────────── */
    {
        lcsas_master_key bad;
        FILE *f = fopen("/tmp/lcsas_garbage_key.json", "w");
        if (f) {
            fputs("{not valid JSON at all", f);
            fclose(f);
        }
        rc = lcsas_repo_load_key_file(
            "/tmp/lcsas_garbage_key.json",
            (const unsigned char *)FIXTURE_PASSWORD,
            strlen(FIXTURE_PASSWORD), &bad
        );
        if (rc == 0) {
            fprintf(stderr, "FAIL: garbage key file accepted\n");
            fails++;
        }
        unlink("/tmp/lcsas_garbage_key.json");
    }

    /* ── lcsas_repo_decrypt direct call ────────────────────────────── */
    {
        unsigned char plain[256];
        size_t plain_len = sizeof plain;

        /* Too short — must fail the STRUCTURAL check with generic -1,
         * distinct from the MAC-mismatch code, so a truncated key file
         * is never mistaken for a rejected password (#384 round 2). */
        unsigned char tiny[32] = {0};
        rc = lcsas_repo_decrypt(&mk, tiny, sizeof tiny, plain, &plain_len);
        if (rc == 0) {
            fprintf(stderr, "FAIL: decrypt accepted <33-byte input\n");
            fails++;
        } else if (rc == LCSAS_REPO_ERR_MAC) {
            fprintf(stderr,
                    "FAIL: <33-byte input returned MAC code (%d); a too-short "
                    "input computes no MAC and must return generic -1\n", rc);
            fails++;
        }

        /* A full-length buffer with a bad tag must fail as MAC mismatch
         * (the genuine wrong-key signal), distinct from the length
         * check above. */
        {
            unsigned char blob[64];
            size_t j;
            for (j = 0; j < sizeof blob; j++) blob[j] = (unsigned char)j;
            plain_len = sizeof plain;
            rc = lcsas_repo_decrypt(&mk, blob, sizeof blob,
                                    plain, &plain_len);
            if (rc != LCSAS_REPO_ERR_MAC) {
                fprintf(stderr,
                        "FAIL: bad-tag decrypt rc=%d, want %d (MAC)\n",
                        rc, LCSAS_REPO_ERR_MAC);
                fails++;
            }
        }
    }

    /* ── lcsas_repo_load_index: parse encrypted index, find blobs ──── */
    {
        lcsas_blob_index ix;
        const lcsas_blob_loc *loc;
        lcsas_blob_index_init(&ix);
        rc = lcsas_repo_load_index(repo, &mk, &ix);
        if (rc != 0) {
            fprintf(stderr, "FAIL: load_index rc=%d\n", rc);
            fails++;
        }
        if (ix.count != 18) {
            fprintf(stderr, "FAIL: index count=%zu, want 18\n", ix.count);
            fails++;
        }

        /* Find data blob */
        lcsas_hex_decode(FIXTURE_DATA_BLOB_HEX, 32, data_id);
        loc = lcsas_blob_index_find(&ix, data_id);
        if (!loc) {
            fprintf(stderr, "FAIL: data blob not in index\n");
            fails++;
        } else if (loc->is_tree) {
            fprintf(stderr, "FAIL: data blob mis-typed as tree\n");
            fails++;
        }

        /* Find tree blob */
        lcsas_hex_decode(FIXTURE_TREE_BLOB_HEX, 32, tree_id);
        loc = lcsas_blob_index_find(&ix, tree_id);
        if (!loc) {
            fprintf(stderr, "FAIL: tree blob not in index\n");
            fails++;
        } else if (!loc->is_tree) {
            fprintf(stderr, "FAIL: tree blob mis-typed as data\n");
            fails++;
        }

        /* Missing blob lookup. */
        {
            unsigned char missing[32];
            memset(missing, 0xFF, 32);
            loc = lcsas_blob_index_find(&ix, missing);
            if (loc != NULL) {
                fprintf(stderr, "FAIL: missing blob returned non-NULL\n");
                fails++;
            }
        }

        lcsas_blob_index_free(&ix);
    }

    /* ── T1C-01: clamped JSON ceiling makes load_index FAIL LOUD ────── */
    /* With lcsas_json_max_tok_bytes clamped tiny, the index file can no
     * longer be tokenized.  The old code silently skipped such files and
     * returned success with an empty index (then later: cryptic "blob
     * not in index").  The fix returns <0 instead — better to fail at
     * load than to half-restore. */
    {
        lcsas_blob_index ix;
        size_t saved = lcsas_json_max_tok_bytes;
        lcsas_blob_index_init(&ix);
        lcsas_json_max_tok_bytes = sizeof(lcsas_json_tok); /* 1 token */
        rc = lcsas_repo_load_index(repo, &mk, &ix);
        lcsas_json_max_tok_bytes = saved;
        if (rc >= 0) {
            fprintf(stderr,
                    "FAIL: load_index returned %d with clamped JSON ceiling; "
                    "must fail loud (<0), not silently drop the index\n", rc);
            fails++;
        }
        lcsas_blob_index_free(&ix);
    }

    /* ── T1C-02: oversized blob `length` is range-rejected ──────────── */
    /* The fixture's seventh index file declares two bad blobs: "ab"*32
     * with a length that overflows long long (caught by decode_int) and
     * "ba"*32 with a 1 TiB length that decodes but exceeds the 512 MiB
     * cap (caught by parse_blob_entry's range check).  load_index must
     * still succeed (per-entry skip), but neither blob may appear in the
     * merged index — proving both were rejected before any
     * need_end/malloc/pread.  ix.count stays 16. */
    {
        lcsas_blob_index ix;
        const lcsas_blob_loc *loc;
        unsigned char bad_id[32];
        lcsas_blob_index_init(&ix);
        rc = lcsas_repo_load_index(repo, &mk, &ix);
        if (rc != 0) {
            fprintf(stderr, "FAIL: T1C-02 load_index rc=%d\n", rc);
            fails++;
        }
        if (ix.count != 18) {
            fprintf(stderr, "FAIL: T1C-02 index count=%zu, want 18 "
                    "(oversized entries must be dropped)\n", ix.count);
            fails++;
        }
        memset(bad_id, 0xAB, 32);
        loc = lcsas_blob_index_find(&ix, bad_id);
        if (loc != NULL) {
            fprintf(stderr, "FAIL: T1C-02 overflow-length blob was "
                    "accepted into the index\n");
            fails++;
        }
        memset(bad_id, 0xBA, 32);
        loc = lcsas_blob_index_find(&ix, bad_id);
        if (loc != NULL) {
            fprintf(stderr, "FAIL: T1C-02 over-cap-length blob was "
                    "accepted into the index\n");
            fails++;
        }
        lcsas_blob_index_free(&ix);
    }

    /* ── lcsas_repo_load_snapshots ──────────────────────────────────── */
    {
        lcsas_snapshot_list snaps;
        long sidx;
        lcsas_snapshot_list_init(&snaps);
        rc = lcsas_repo_load_snapshots(repo, &mk, &snaps);
        if (rc != 0) {
            fprintf(stderr, "FAIL: load_snapshots rc=%d\n", rc);
            fails++;
        }
        if (snaps.count != 3) {
            fprintf(stderr, "FAIL: snap count=%zu, want 3\n", snaps.count);
            fails++;
        }
        sidx = lcsas_snapshot_latest(&snaps);
        if (sidx < 0) {
            fprintf(stderr, "FAIL: snapshot_latest returned -1\n");
            fails++;
        }
        /* snapshot tree should match fixture's tree blob */
        if (sidx >= 0
                && strcmp(snaps.items[sidx].tree_id_hex,
                          FIXTURE_TREE_BLOB_HEX) != 0) {
            fprintf(stderr, "FAIL: snapshot tree=%s want %s\n",
                    snaps.items[sidx].tree_id_hex, FIXTURE_TREE_BLOB_HEX);
            fails++;
        }
        /* Regression guard for #194: load_snapshots must leave the
         * array sorted ASCENDING by ISO-8601 `time` so that
         * items[count-1] is the chronologically newest snapshot.
         * Monotonic non-decreasing implies items[count-1] is max,
         * so one pairwise pass over the array suffices. */
        {
            size_t k;
            for (k = 1; k < snaps.count; k++) {
                if (strcmp(snaps.items[k - 1].time,
                           snaps.items[k].time) > 0) {
                    fprintf(stderr,
                            "FAIL: snapshots not sorted ascending by "
                            "time: items[%zu].time=%s > items[%zu].time=%s\n",
                            k - 1, snaps.items[k - 1].time,
                            k, snaps.items[k].time);
                    fails++;
                }
            }
        }
        /* snapshot_find by exact ID */
        if (sidx >= 0) {
            long found = lcsas_snapshot_find(&snaps, snaps.items[sidx].file_name);
            if (found != sidx) {
                fprintf(stderr, "FAIL: snapshot_find exact returned %ld\n", found);
                fails++;
            }
        }
        /* snapshot_find by short prefix */
        if (sidx >= 0) {
            char prefix[9];
            memcpy(prefix, snaps.items[sidx].file_name, 8);
            prefix[8] = '\0';
            if (lcsas_snapshot_find(&snaps, prefix) != sidx) {
                fprintf(stderr, "FAIL: snapshot_find prefix failed\n");
                fails++;
            }
        }
        /* snapshot_find missing returns -1 */
        if (lcsas_snapshot_find(&snaps, "deadbeefdeadbeef") != -1) {
            fprintf(stderr, "FAIL: snapshot_find missing returned !=-1\n");
            fails++;
        }
        lcsas_snapshot_list_free(&snaps);
    }

    /* ── empty snapshot_list latest returns -1 ─────────────────────── */
    {
        lcsas_snapshot_list empty;
        lcsas_snapshot_list_init(&empty);
        if (lcsas_snapshot_latest(&empty) != -1) {
            fprintf(stderr, "FAIL: latest(empty) should be -1\n");
            fails++;
        }
        lcsas_snapshot_list_free(&empty);
    }

    /* ── lcsas_repo_read_blob: full pipeline ──────────────────────── */
    {
        lcsas_blob_index ix;
        const lcsas_blob_loc *loc;
        unsigned char *blob = NULL;
        size_t blob_len = 0;
        lcsas_blob_index_init(&ix);
        if (lcsas_repo_load_index(repo, &mk, &ix) == 0) {
            loc = lcsas_blob_index_find(&ix, data_id);
            if (loc) {
                rc = lcsas_repo_read_blob(repo, &mk, loc, NULL,
                                          &blob, &blob_len);
                if (rc != 0) {
                    fprintf(stderr, "FAIL: read_blob rc=%d\n", rc);
                    fails++;
                } else {
                    const char *expect =
                        "hello from lcsas-restore fixture\n";
                    if (blob_len != strlen(expect)
                            || memcmp(blob, expect, blob_len) != 0) {
                        fprintf(stderr,
                                "FAIL: data blob content mismatch "
                                "(got %zu bytes)\n", blob_len);
                        fails++;
                    }
                    free(blob);
                }
            }
        }
        lcsas_blob_index_free(&ix);
    }

    /* ── RST-02: zstd-magic blob stored UNcompressed reads verbatim ── */
    {
        lcsas_blob_index ix;
        const lcsas_blob_loc *loc;
        unsigned char zmagic_id[32];
        unsigned char *blob = NULL;
        size_t blob_len = 0;
        lcsas_blob_index_init(&ix);
        if (lcsas_repo_load_index(repo, &mk, &ix) == 0) {
            lcsas_hex_decode(FIXTURE_ZMAGIC_BLOB_HEX, 32, zmagic_id);
            loc = lcsas_blob_index_find(&ix, zmagic_id);
            if (!loc) {
                fprintf(stderr, "FAIL: zmagic blob not in index\n");
                fails++;
            } else {
                /* Index entry must NOT carry uncompressed_length. */
                if (loc->uncompressed_length > 0) {
                    fprintf(stderr,
                            "FAIL: zmagic blob has unexpected "
                            "uncompressed_length=%lld\n",
                            (long long)loc->uncompressed_length);
                    fails++;
                }
                rc = lcsas_repo_read_blob(repo, &mk, loc, NULL,
                                          &blob, &blob_len);
                if (rc != 0) {
                    /* Pre-fix: magic-sniff decompresses, hash mismatch,
                     * rc != 0.  Post-fix: returned verbatim, rc == 0. */
                    fprintf(stderr,
                            "FAIL: zmagic read_blob rc=%d "
                            "(false decompression?)\n", rc);
                    fails++;
                } else {
                    /* read_blob's own sha256 check already proves byte
                     * identity; assert the bytes are still the raw zstd
                     * frame (would be the decompressed payload if the bug
                     * had fired). */
                    if (blob_len < 4
                            || blob[0] != 0x28 || blob[1] != 0xb5
                            || blob[2] != 0x2f || blob[3] != 0xfd) {
                        fprintf(stderr,
                                "FAIL: zmagic blob not returned verbatim "
                                "(len=%zu)\n", blob_len);
                        fails++;
                    }
                    free(blob);
                }
            }
        }
        lcsas_blob_index_free(&ix);
    }

    /* ── lcsas_tree_restore: full end-to-end materialisation ─────── */
    {
        lcsas_blob_index ix;
        char target[] = "/tmp/lcsas_test_repo_target_XXXXXX";
        char hello_path[1024];
        char read_buf[256];
        FILE *f;
        size_t got;
        lcsas_blob_index_init(&ix);
        if (lcsas_repo_load_index(repo, &mk, &ix) != 0) {
            fprintf(stderr, "FAIL: load_index for tree restore\n"); fails++;
        }
        if (mkdtemp(target) == NULL) {
            fprintf(stderr, "FAIL: mkdtemp\n"); fails++;
        }

        rc = lcsas_tree_restore(
            repo, &mk, &ix, FIXTURE_TREE_BLOB_HEX, target, target,
            NULL, NULL
        );
        if (rc != 0) {
            fprintf(stderr, "FAIL: tree_restore rc=%d\n", rc); fails++;
        }

        /* Verify the file was created with correct content. */
        snprintf(hello_path, sizeof hello_path, "%s/hello.txt", target);
        f = fopen(hello_path, "rb");
        if (!f) {
            fprintf(stderr, "FAIL: hello.txt not created\n"); fails++;
        } else {
            got = fread(read_buf, 1, sizeof read_buf - 1, f);
            read_buf[got] = '\0';
            if (strcmp(read_buf, "hello from lcsas-restore fixture\n") != 0) {
                fprintf(stderr, "FAIL: hello.txt content: %s\n", read_buf);
                fails++;
            }
            fclose(f);
        }

        /* Sub-directory must be restored, with the empty file inside. */
        {
            char sub_path[1024];
            struct stat st;
            snprintf(sub_path, sizeof sub_path, "%s/subdir", target);
            if (stat(sub_path, &st) != 0 || !S_ISDIR(st.st_mode)) {
                fprintf(stderr, "FAIL: subdir not created\n"); fails++;
            }
            snprintf(sub_path, sizeof sub_path, "%s/subdir/empty.txt", target);
            if (stat(sub_path, &st) != 0 || !S_ISREG(st.st_mode)) {
                fprintf(stderr, "FAIL: subdir/empty.txt missing\n"); fails++;
            } else if (st.st_size != 0) {
                fprintf(stderr, "FAIL: empty.txt size=%lld, want 0\n",
                        (long long)st.st_size);
                fails++;
            }
        }

        /* Symlink: hello.txt's link.txt must exist as a symlink. */
        {
            char link_path[1024];
            struct stat lst;
            char link_target[256];
            ssize_t llen;
            snprintf(link_path, sizeof link_path, "%s/link.txt", target);
            if (lstat(link_path, &lst) != 0 || !S_ISLNK(lst.st_mode)) {
                fprintf(stderr, "FAIL: link.txt not a symlink\n"); fails++;
            } else {
                llen = readlink(link_path, link_target, sizeof link_target - 1);
                if (llen < 0) {
                    fprintf(stderr, "FAIL: readlink failed\n"); fails++;
                } else {
                    link_target[llen] = '\0';
                    if (strcmp(link_target, "hello.txt") != 0) {
                        fprintf(stderr,
                                "FAIL: link.txt -> %s (want hello.txt)\n",
                                link_target);
                        fails++;
                    }
                }
            }
        }

        /* xattr_test_file must be restored with correct content. */
        {
            char xattr_path[1024];
            char xattr_buf[64];
            FILE *xf;
            size_t xgot;
            snprintf(xattr_path, sizeof xattr_path,
                     "%s/xattr_test_file", target);
            xf = fopen(xattr_path, "rb");
            if (!xf) {
                fprintf(stderr, "FAIL: xattr_test_file not created\n");
                fails++;
            } else {
                xgot = fread(xattr_buf, 1, sizeof xattr_buf - 1, xf);
                xattr_buf[xgot] = '\0';
                if (strcmp(xattr_buf, "xattr test content") != 0) {
                    fprintf(stderr,
                            "FAIL: xattr_test_file content: '%s'\n",
                            xattr_buf);
                    fails++;
                }
                fclose(xf);
            }
        }

        /* hardlink_a and hardlink_b must both be restored and share
         * the same inode (confirming the link() path was taken). */
        {
            char hla[1024], hlb[1024];
            struct stat sta, stb;
            snprintf(hla, sizeof hla, "%s/hardlink_a", target);
            snprintf(hlb, sizeof hlb, "%s/hardlink_b", target);
            if (stat(hla, &sta) != 0) {
                fprintf(stderr, "FAIL: hardlink_a not created\n");
                fails++;
            }
            if (stat(hlb, &stb) != 0) {
                fprintf(stderr, "FAIL: hardlink_b not created\n");
                fails++;
            }
            if (sta.st_ino != stb.st_ino) {
                fprintf(stderr,
                        "FAIL: hardlink_a inode=%llu != hardlink_b "
                        "inode=%llu (link() path not taken)\n",
                        (unsigned long long)sta.st_ino,
                        (unsigned long long)stb.st_ino);
                fails++;
            }
        }

        /* Unsafe-named node ("../escape") must NOT have been created. */
        {
            char esc[1024];
            struct stat es;
            snprintf(esc, sizeof esc, "%s/../escape", target);
            if (stat(esc, &es) == 0) {
                fprintf(stderr, "FAIL: '../escape' was materialized!\n");
                fails++;
                unlink(esc);
            }
        }

        /* Unsupported chardev node must be skipped (not crash). */
        {
            char dev[1024];
            struct stat ds;
            snprintf(dev, sizeof dev, "%s/device.dev", target);
            if (stat(dev, &ds) == 0) {
                fprintf(stderr, "FAIL: chardev node was materialized\n");
                fails++;
            }
        }

        /* Re-run tree_restore: should be idempotent (Issue #92 resume).
         * The "already restored, skipping" code path in tree.c
         * (lines 114-119) must trigger because the target file exists
         * with the expected size. */
        rc = lcsas_tree_restore(
            repo, &mk, &ix, FIXTURE_TREE_BLOB_HEX, target, target,
            NULL, NULL
        );
        if (rc != 0) {
            fprintf(stderr, "FAIL: tree_restore re-run rc=%d\n", rc);
            fails++;
        }

        /* Wrong tree ID: must fail cleanly (no crash). */
        rc = lcsas_tree_restore(
            repo, &mk, &ix,
            "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
            target, target, NULL, NULL
        );
        if (rc == 0) {
            fprintf(stderr, "FAIL: missing tree ID accepted\n");
            fails++;
        }

        /* Progress reporting: rerun with progress enabled. */
        {
            lcsas_progress prog;
            char target2[] = "/tmp/lcsas_test_repo_target2_XXXXXX";
            lcsas_progress_init(&prog, ix.count);
            prog.enabled = 1;
            if (mkdtemp(target2)) {
                lcsas_tree_restore(repo, &mk, &ix, FIXTURE_TREE_BLOB_HEX,
                                    target2, target2, NULL, &prog);
                lcsas_progress_finish(&prog);
                /* Cleanup target2. */
                {
                    char cmd[1024];
                    snprintf(cmd, sizeof cmd, "rm -rf %s", target2);
                    (void)system(cmd);
                }
            }
        }

        /* Broken tree #1: file references a blob NOT in the index.
         * tree.c restore_file_node should hit the "blob not in index"
         * branch and return -1.  lcsas_tree_restore propagates the
         * failure (goto out → rc stays -1). */
        {
            char tdir[] = "/tmp/lcsas_test_broken_XXXXXX";
            if (mkdtemp(tdir)) {
                int rc2 = lcsas_tree_restore(
                    repo, &mk, &ix, FIXTURE_BROKEN_TREE_HEX, tdir, tdir,
                    NULL, NULL
                );
                if (rc2 == 0) {
                    fprintf(stderr,
                            "FAIL: broken tree (missing blob) should fail "
                            "but rc=0\n");
                    fails++;
                }
                {
                    char cmd[1024];
                    snprintf(cmd, sizeof cmd, "rm -rf %s", tdir);
                    (void)system(cmd);
                }
            }
        }

        /* Broken tree #2: file content has non-hex characters in a
         * 64-char string.  tree.c hex_decode returns -1 in
         * restore_file_node. */
        {
            char tdir[] = "/tmp/lcsas_test_bad_hex_XXXXXX";
            if (mkdtemp(tdir)) {
                int rc2 = lcsas_tree_restore(
                    repo, &mk, &ix, FIXTURE_BAD_HEX_TREE_HEX, tdir, tdir,
                    NULL, NULL
                );
                if (rc2 == 0) {
                    fprintf(stderr,
                            "FAIL: bad-hex tree should fail but rc=0\n");
                    fails++;
                }
                {
                    char cmd[1024];
                    snprintf(cmd, sizeof cmd, "rm -rf %s", tdir);
                    (void)system(cmd);
                }
            }
        }

        /* Tree blob whose content references a blob in a pack that
         * does NOT exist on disk.  restore_file_node calls
         * lcsas_repo_read_blob which can't find the pack and returns
         * -1 → tree.c:157 (rc = -1; break). */
        {
            char tdir[] = "/tmp/lcsas_test_miss_content_XXXXXX";
            if (mkdtemp(tdir)) {
                int rc2 = lcsas_tree_restore(
                    repo, &mk, &ix, FIXTURE_MISSING_CONTENT_TREE_HEX,
                    tdir, tdir, NULL, NULL
                );
                if (rc2 == 0) {
                    fprintf(stderr,
                            "FAIL: missing-content tree should fail rc=0\n");
                    fails++;
                }
                {
                    char cmd[1024];
                    snprintf(cmd, sizeof cmd, "rm -rf %s", tdir);
                    (void)system(cmd);
                }
            }
        }

        /* Tree blob whose own pack does NOT exist on disk.  The
         * lcsas_repo_read_blob for the tree blob itself fails →
         * tree.c:201 (return -1) and repo.c:833-834 ("pack not found"). */
        {
            char tdir[] = "/tmp/lcsas_test_miss_tree_XXXXXX";
            if (mkdtemp(tdir)) {
                int rc2 = lcsas_tree_restore(
                    repo, &mk, &ix, FIXTURE_MISSING_TREE_HEX,
                    tdir, tdir, NULL, NULL
                );
                if (rc2 == 0) {
                    fprintf(stderr,
                            "FAIL: missing-tree blob should fail rc=0\n");
                    fails++;
                }
                {
                    char cmd[1024];
                    snprintf(cmd, sizeof cmd, "rm -rf %s", tdir);
                    (void)system(cmd);
                }
            }
        }

        /* Tree where "nodes" is a string (not an array).  Hits tree.c
         * line 213: rc = 0; goto out; — a soft skip (rc stays 0). */
        {
            char tdir[] = "/tmp/lcsas_test_wrong_nodes_XXXXXX";
            if (mkdtemp(tdir)) {
                int rc2 = lcsas_tree_restore(
                    repo, &mk, &ix, FIXTURE_WRONG_NODES_TREE_HEX,
                    tdir, tdir, NULL, NULL
                );
                /* Wrong-type "nodes" causes a graceful skip (rc=0). */
                if (rc2 != 0) {
                    fprintf(stderr,
                            "FAIL: wrong-nodes-type should rc=0, got %d\n",
                            rc2);
                    fails++;
                }
                {
                    char cmd[1024];
                    snprintf(cmd, sizeof cmd, "rm -rf %s", tdir);
                    (void)system(cmd);
                }
            }
        }

        /* Tree with a node name > 1024 bytes — exercises tree.c line 240
         * (name decode_string returns -1, loop continues).  Walk
         * completes with rc=0 because the offending node is just
         * skipped. */
        {
            char tdir[] = "/tmp/lcsas_test_long_name_XXXXXX";
            if (mkdtemp(tdir)) {
                int rc2 = lcsas_tree_restore(
                    repo, &mk, &ix, FIXTURE_LONG_NAME_TREE_HEX,
                    tdir, tdir, NULL, NULL
                );
                if (rc2 != 0) {
                    fprintf(stderr,
                            "FAIL: long-name tree should rc=0, got %d\n", rc2);
                    fails++;
                }
                {
                    char cmd[1024];
                    snprintf(cmd, sizeof cmd, "rm -rf %s", tdir);
                    (void)system(cmd);
                }
            }
        }

        /* Tree with a node type > 32 bytes — exercises tree.c line 243
         * (type decode_string returns -1, loop continues). */
        {
            char tdir[] = "/tmp/lcsas_test_long_type_XXXXXX";
            if (mkdtemp(tdir)) {
                int rc2 = lcsas_tree_restore(
                    repo, &mk, &ix, FIXTURE_LONG_TYPE_TREE_HEX,
                    tdir, tdir, NULL, NULL
                );
                if (rc2 != 0) {
                    fprintf(stderr,
                            "FAIL: long-type tree should rc=0, got %d\n", rc2);
                    fails++;
                }
                {
                    char cmd[1024];
                    snprintf(cmd, sizeof cmd, "rm -rf %s", tdir);
                    (void)system(cmd);
                }
            }
        }

        /* T1C-03: nul-name tree.  A legitimate "evil" file plus a
         * hostile "evil\0x" (JSON ` ` escape) both reduce to
         * basename "evil" under C-string truncation.  The hostile node
         * must be skipped (embedded NUL) so it never overwrites the
         * sibling.  Assert the restore succeeds (rc=0, skip-and-
         * continue) AND that "evil" holds the SIBLING's content, not
         * the hostile node's. */
        {
            char tdir[] = "/tmp/lcsas_test_nul_name_XXXXXX";
            if (mkdtemp(tdir)) {
                int rc2 = lcsas_tree_restore(
                    repo, &mk, &ix, FIXTURE_NUL_NAME_TREE_HEX,
                    tdir, tdir, NULL, NULL
                );
                if (rc2 != 0) {
                    fprintf(stderr,
                            "FAIL: nul-name tree should rc=0, got %d\n", rc2);
                    fails++;
                }
                {
                    char path[1100];
                    char buf[256];
                    FILE *f;
                    size_t n;
                    snprintf(path, sizeof path, "%s/evil", tdir);
                    f = fopen(path, "rb");
                    if (!f) {
                        fprintf(stderr,
                                "FAIL: nul-name 'evil' not restored\n");
                        fails++;
                    } else {
                        n = fread(buf, 1, sizeof buf - 1, f);
                        fclose(f);
                        buf[n] = '\0';
                        if (strcmp(buf, FIXTURE_NUL_SIBLING_CONTENT) != 0) {
                            fprintf(stderr,
                                    "FAIL: nul-name collision — 'evil' has "
                                    "wrong content: %s\n", buf);
                            fails++;
                        }
                    }
                }
                {
                    char cmd[1024];
                    snprintf(cmd, sizeof cmd, "rm -rf %s", tdir);
                    (void)system(cmd);
                }
            }
        }

        /* Broken tree #3: a dir node whose subtree is the broken tree
         * above.  lcsas_tree_restore recurses into the dir, the
         * recursive call fails, and the outer call goto-out's. */
        {
            char tdir[] = "/tmp/lcsas_test_bad_subdir_XXXXXX";
            if (mkdtemp(tdir)) {
                int rc2 = lcsas_tree_restore(
                    repo, &mk, &ix, FIXTURE_BAD_SUBDIR_TREE_HEX,
                    tdir, tdir, NULL, NULL
                );
                if (rc2 == 0) {
                    fprintf(stderr,
                            "FAIL: bad-subdir tree should fail but rc=0\n");
                    fails++;
                }
                {
                    char cmd[1024];
                    snprintf(cmd, sizeof cmd, "rm -rf %s", tdir);
                    (void)system(cmd);
                }
            }
        }

        /* Cleanup target. */
        {
            char cmd[1024];
            snprintf(cmd, sizeof cmd, "rm -rf %s", target);
            (void)system(cmd);
        }
        lcsas_blob_index_free(&ix);
    }

    /* ── lcsas_parse_iso8601_utc: TZ-offset + edge-case coverage ──── *
     * Issue #257 — the parser supports `Z`, `+HH:MM`, and `-HH:MM`.
     * The fixture only emits `Z` so the offset branches (lcsas_io.c
     * lines 233-240, 261-262) need explicit unit coverage.            */
    {
        long long sec = 0;
        long nsec = 0;

        /* Positive TZ offset (e.g. +05:30 -> sec is shifted EAST of UTC). */
        if (lcsas_parse_iso8601_utc("2026-05-21T05:30:00+05:30", &sec, &nsec) != 0) {
            fprintf(stderr, "FAIL: iso8601 +05:30 parse failed\n");
            fails++;
        } else if (sec != 1747787400LL || nsec != 0) {
            /* +05:30 means the wall clock is 5h30 ahead of UTC, so the
             * UTC instant is 2026-05-21T00:00:00Z = 1747785600 epoch.
             * Allow either convention as long as the offset was honoured
             * (i.e. result != naive parse of YYYY-MM-DDTHH:MM:SS). */
            if (sec == 1747805400LL) {
                fprintf(stderr,
                        "FAIL: iso8601 +05:30 not applied (sec=%lld)\n", sec);
                fails++;
            }
        }

        /* Negative TZ offset (-08:00). */
        if (lcsas_parse_iso8601_utc("2026-01-15T12:00:00-08:00", &sec, &nsec) != 0) {
            fprintf(stderr, "FAIL: iso8601 -08:00 parse failed\n");
            fails++;
        }

        /* Missing timezone -> reject (lcsas_io.c:240). */
        if (lcsas_parse_iso8601_utc("2026-05-21T05:30:00", &sec, &nsec) == 0) {
            fprintf(stderr, "FAIL: iso8601 missing TZ should fail\n");
            fails++;
        }

        /* Lowercase 'z' alias for Zulu. */
        if (lcsas_parse_iso8601_utc("2026-05-21T05:30:00z", &sec, &nsec) != 0) {
            fprintf(stderr, "FAIL: iso8601 lowercase z should parse\n");
            fails++;
        }

        /* Fractional seconds with TZ offset. */
        if (lcsas_parse_iso8601_utc("2026-05-21T05:30:00.123456789+01:00",
                                    &sec, &nsec) != 0) {
            fprintf(stderr, "FAIL: iso8601 fractional + TZ failed\n");
            fails++;
        }
    }

    /* ── T1C-05: an index file over the 256 MiB decompress cap is FATAL ─
     * A v2-zstd index whose frame HEADER declares 300 MiB of content (a
     * tiny crafted frame — no need to actually materialise 300 MiB) makes
     * decrypt_repo_file return NULL with LCSAS_DEC_TOOBIG.  Before this
     * fix both load_index passes treated that NULL as a silent skip and
     * returned success with the index — and every blob it described —
     * missing, surfacing much later as a cryptic "blob not in index".
     * load_index must now fail loud (<0) BEFORE any restore I/O. */
    {
        char tmp[] = "/tmp/lcsas_t1c05_toobig_XXXXXX";
        char idx_path[1024];
        lcsas_blob_index ix;
        unsigned char iv[16];
        unsigned char frame[5 + 13];
        unsigned long long fcs = 300ULL * 1024 * 1024;
        int b;
        /* 64-hex name so load_index does not pre-skip it. */
        const char *name =
            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";

        memset(iv, 0, 16); iv[0] = 0x21;   /* unique IV for this fixture */
        /* v2 prefix byte 0x02, then a minimal zstd frame whose header
         * declares an 8-byte content size of 300 MiB:
         *   magic 28 b5 2f fd | desc 0xE0 (FCS=8B, single-segment) | FCS. */
        frame[0] = 0x02;
        frame[1] = 0x28; frame[2] = 0xb5; frame[3] = 0x2f; frame[4] = 0xfd;
        frame[5] = 0xE0;
        for (b = 0; b < 8; b++)
            frame[6 + b] = (unsigned char)((fcs >> (8 * b)) & 0xFF);

        if (mkdtemp(tmp) == NULL) {
            fprintf(stderr, "FAIL: T1C-05 mkdtemp\n"); fails++;
        } else if (copy_valid_indexes(repo, tmp) != 0) {
            fprintf(stderr, "FAIL: T1C-05 copy_valid_indexes\n"); fails++;
        } else {
            snprintf(idx_path, sizeof idx_path, "%s/index/%s", tmp, name);
            if (enc_write(&mk, iv, frame, sizeof frame, idx_path) != 0) {
                fprintf(stderr, "FAIL: T1C-05 enc_write toobig\n"); fails++;
            } else {
                fprintf(stderr,
                        "[test_repo] T1C-05 expecting cap ERROR below:\n");
                lcsas_blob_index_init(&ix);
                rc = lcsas_repo_load_index(tmp, &mk, &ix);
                if (rc >= 0) {
                    fprintf(stderr,
                            "FAIL: T1C-05 over-cap index did not fail load "
                            "(rc=%d); must be fatal, not a silent skip\n", rc);
                    fails++;
                }
                /* The valid index files were also present; load must NOT
                 * have half-succeeded with their blobs.  rc<0 is the
                 * contract; the index may hold partial entries from pass 2
                 * before it tripped, so we only assert the failure code. */
                lcsas_blob_index_free(&ix);
            }
        }
    }

    /* ── T1C-05 companion: a MAC-corrupt index alongside a valid one ────
     * still loads (warn + skip + summary count).  This pins the
     * petabyte/BUG-3 premise: authentication failure on one stray index
     * file must NOT sink the whole load — only the provably-unreadable
     * cap/zstd cases are fatal. */
    {
        char tmp[] = "/tmp/lcsas_t1c05_macbad_XXXXXX";
        char idx_path[1024];
        lcsas_blob_index ix;
        const lcsas_blob_loc *loc;
        unsigned char iv[16];
        unsigned char junk[64];
        size_t k;
        const char *name =
            "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";

        memset(iv, 0, 16); iv[0] = 0x22;
        for (k = 0; k < sizeof junk; k++) junk[k] = (unsigned char)k;

        if (mkdtemp(tmp) == NULL) {
            fprintf(stderr, "FAIL: T1C-05 macbad mkdtemp\n"); fails++;
        } else if (copy_valid_indexes(repo, tmp) != 0) {
            fprintf(stderr, "FAIL: T1C-05 macbad copy_valid_indexes\n");
            fails++;
        } else {
            FILE *bad;
            int wrote_bad = 0;
            /* Write a MAC-valid file then corrupt its tag so
             * lcsas_repo_decrypt fails (LCSAS_DEC_MAC, non-fatal). */
            snprintf(idx_path, sizeof idx_path, "%s/index/%s", tmp, name);
            if (enc_write(&mk, iv, junk, sizeof junk, idx_path) == 0) {
                bad = fopen(idx_path, "r+b");
                if (bad) {
                    /* Flip the last byte (part of the Poly1305 tag). */
                    unsigned char b;
                    if (fseek(bad, -1, SEEK_END) == 0
                            && fread(&b, 1, 1, bad) == 1) {
                        b ^= 0xFF;
                        if (fseek(bad, -1, SEEK_END) == 0)
                            fwrite(&b, 1, 1, bad);
                    }
                    fclose(bad);
                    wrote_bad = 1;
                }
            }
            if (!wrote_bad) {
                fprintf(stderr, "FAIL: T1C-05 macbad setup\n"); fails++;
            } else {
                fprintf(stderr,
                        "[test_repo] T1C-05 expecting auth WARNING below:\n");
                lcsas_blob_index_init(&ix);
                rc = lcsas_repo_load_index(tmp, &mk, &ix);
                if (rc != 0) {
                    fprintf(stderr,
                            "FAIL: T1C-05 MAC-corrupt index made load fatal "
                            "(rc=%d); must warn+skip, not abort\n", rc);
                    fails++;
                }
                /* The genuine fixture blobs must still be present. */
                lcsas_hex_decode(FIXTURE_DATA_BLOB_HEX, 32, data_id);
                loc = lcsas_blob_index_find(&ix, data_id);
                if (!loc) {
                    fprintf(stderr,
                            "FAIL: T1C-05 valid blobs lost when a sibling "
                            "index failed MAC\n");
                    fails++;
                }
                lcsas_blob_index_free(&ix);
            }
        }
    }

    if (fails == 0) printf("test_repo: OK\n");
    return fails ? 1 : 0;
}
