/*
 * test_zstd.c -- vendored zstd decoder round-trip.
 *
 * We don't have a zstd encoder in this build, so we hard-code a known
 * zstd frame produced by `zstd --ultra -22` on a deterministic input.
 * Verifies both probe and full decode paths.
 */
#include "zstd_dec.h"
#include <stdio.h>
#include <string.h>

static int fails = 0;

/*
 * zstd frame produced by:
 *   echo -n "Hello, LCSAS zstd! Hello, LCSAS zstd! Hello, LCSAS zstd!" \
 *       | zstd --ultra -22 -
 * (56-byte plaintext, repeated "Hello, LCSAS zstd! " * 3 minus trailing space)
 *
 * We embed the frame as a byte array.
 */
static const unsigned char ZSTD_FRAME[] = {
    0x28, 0xb5, 0x2f, 0xfd, 0x20, 0x38, 0xd5, 0x00, 0x00, 0xa0, 0x48, 0x65,
    0x6c, 0x6c, 0x6f, 0x2c, 0x20, 0x4c, 0x43, 0x53, 0x41, 0x53, 0x20, 0x7a,
    0x73, 0x74, 0x64, 0x21, 0x20, 0x48, 0x01, 0x00, 0x1a, 0x39, 0x99
};

static const char EXPECTED[] =
    "Hello, LCSAS zstd! Hello, LCSAS zstd! Hello, LCSAS zstd!";

int main(void)
{
    char out[256];
    long sz;
    long got;
    unsigned long long fsz;

    sz = lcsas_zstd_decode(ZSTD_FRAME, sizeof ZSTD_FRAME, NULL, 0);
    if (sz != (long)strlen(EXPECTED)) {
        fprintf(stderr, "FAIL probe: got %ld, want %zu\n", sz, strlen(EXPECTED));
        fails++;
    }

    fsz = lcsas_zstd_frame_size(ZSTD_FRAME, sizeof ZSTD_FRAME);
    if (fsz != strlen(EXPECTED)) {
        fprintf(stderr, "FAIL frame_size: got %llu, want %zu\n",
                (unsigned long long)fsz, strlen(EXPECTED));
        fails++;
    }

    got = lcsas_zstd_decode(ZSTD_FRAME, sizeof ZSTD_FRAME, out, sizeof out);
    if (got < 0 || (size_t)got != strlen(EXPECTED)
            || memcmp(out, EXPECTED, strlen(EXPECTED)) != 0) {
        fprintf(stderr, "FAIL decode: got=%ld\n", got);
        if (got >= 0) {
            fwrite(out, 1, (size_t)got, stderr);
            fputc('\n', stderr);
        }
        fails++;
    }

    /* Truncated input should fail cleanly. */
    if (lcsas_zstd_decode(ZSTD_FRAME, 4, out, sizeof out) >= 0) {
        fprintf(stderr, "FAIL: truncated frame should error\n");
        fails++;
    }

    /* Garbage input should trigger CONTENTSIZE_ERROR in the probe path. */
    {
        static const unsigned char GARBAGE[16] = {
            0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
            0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff
        };
        long g = lcsas_zstd_decode(GARBAGE, sizeof GARBAGE, NULL, 0);
        if (g >= 0) {
            fprintf(stderr, "FAIL: garbage probe should fail, got %ld\n", g);
            fails++;
        }
        if (lcsas_zstd_frame_size(GARBAGE, sizeof GARBAGE) != 0) {
            fprintf(stderr, "FAIL: garbage frame_size should return 0\n");
            fails++;
        }
    }

    /*
     * Streaming-compressed frame: Frame_Header_Descriptor byte (0x00)
     * has FCS_flag=0 and Single_Segment=0, so the decoder cannot
     * probe the content size up-front (CONTENTSIZE_UNKNOWN path).
     * Verifies the ZSTD_decompressBound fallback in both lcsas_zstd_decode
     * (probe with out=NULL) and lcsas_zstd_frame_size.
     *
     * Generated by:
     *   python3 -c "import zstandard;
     *       co = zstandard.ZstdCompressor().compressobj();
     *       print((co.compress(b'streaming-no-content-size!') + co.flush()).hex())"
     */
    {
        static const unsigned char STREAMING[] = {
            0x28, 0xb5, 0x2f, 0xfd, 0x00, 0x58, 0xd1, 0x00,
            0x00, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69,
            0x6e, 0x67, 0x2d, 0x6e, 0x6f, 0x2d, 0x63, 0x6f,
            0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x69,
            0x7a, 0x65, 0x21
        };
        static const char S_PLAIN[] = "streaming-no-content-size!";
        long probed;
        long got2;
        unsigned long long sz2;

        probed = lcsas_zstd_decode(STREAMING, sizeof STREAMING, NULL, 0);
        if (probed < (long)strlen(S_PLAIN)) {
            fprintf(stderr, "FAIL: streaming probe should return >= %zu, got %ld\n",
                    strlen(S_PLAIN), probed);
            fails++;
        }
        sz2 = lcsas_zstd_frame_size(STREAMING, sizeof STREAMING);
        if (sz2 < strlen(S_PLAIN)) {
            fprintf(stderr, "FAIL: streaming frame_size should return >= %zu, got %llu\n",
                    strlen(S_PLAIN), sz2);
            fails++;
        }
        got2 = lcsas_zstd_decode(STREAMING, sizeof STREAMING, out, sizeof out);
        if (got2 < 0 || (size_t)got2 != strlen(S_PLAIN)
                || memcmp(out, S_PLAIN, strlen(S_PLAIN)) != 0) {
            fprintf(stderr, "FAIL: streaming decode\n");
            fails++;
        }
    }

    if (fails == 0) printf("test_zstd: OK\n");
    return fails ? 1 : 0;
}
