/*
 * test_repo.c -- exercise repo.c against a real encrypted fixture.
 *
 * Uses recovery/tests/fixtures/repo (generated by gen_fixture.py) to
 * test the full restic-format decryption pipeline:
 *
 *   - lcsas_repo_load_key_file          (scrypt + AES-CTR + Poly1305)
 *   - lcsas_repo_load_keys_dir          (scan keys/)
 *   - lcsas_repo_decrypt                (direct AEAD)
 *   - lcsas_repo_load_index             (parse index JSON, find blobs)
 *   - lcsas_repo_load_snapshots         (parse snapshot list)
 *   - lcsas_snapshot_latest / _find     (snapshot lookups)
 *   - lcsas_blob_index_find             (blob lookups)
 *
 * The fixture's expected blob IDs are read from manifest.json and
 * pinned in this test.
 */
#include "repo.h"
#include "tree.h"
#include "hex.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <sys/stat.h>
#include <unistd.h>

static int fails = 0;

/* Fixture-pinned values (regenerate gen_fixture.py changes these). */
#define FIXTURE_PASSWORD       "test"
#define FIXTURE_DATA_BLOB_HEX  \
    "6565160e5ca15054fd190b02fab20e4e7daf41e54d19e649d0798d7aca56c5b2"
#define FIXTURE_TREE_BLOB_HEX  \
    "ee915c16ffdf6f53b74e49f10090923a84d6d3a507bf40b71d05136c5b337425"
#define FIXTURE_PACK_HEX       \
    "ecd0a6e1a59e303bf0b647e20cbddd10469b2a8882664af80cec3a306f54e402"
#define FIXTURE_BROKEN_TREE_HEX  \
    "b9a34a1fa85b4ccdcd91b96abdb97acd76c914ba1f99c0f9c61e08842861add3"
#define FIXTURE_BAD_HEX_TREE_HEX \
    "e9b21400fad094fe6f80db621ec8e68ace890c09875e807db12e9e78d65c884a"
#define FIXTURE_BAD_SUBDIR_TREE_HEX \
    "8d615e95dd9cd90bb4a14ee546624b8230280e4b31597c28fff105d7e8eb12f1"

/* Locate the fixture directory.  Honour LCSAS_TEST_FIXTURE_DIR for
 * out-of-tree builds; otherwise assume cwd is repo root or recovery/. */
static const char *fixture_path(char *buf, size_t cap)
{
    const char *override = getenv("LCSAS_TEST_FIXTURE_DIR");
    if (override) {
        snprintf(buf, cap, "%s", override);
        return buf;
    }
    snprintf(buf, cap, "recovery/tests/fixtures/repo");
    if (access(buf, F_OK) == 0) return buf;
    snprintf(buf, cap, "tests/fixtures/repo");
    return buf;
}

int
main(void)
{
    char repo_buf[1024];
    char path[1024];
    const char *repo;
    lcsas_master_key mk;
    int rc;
    unsigned char data_id[32], tree_id[32];

    repo = fixture_path(repo_buf, sizeof repo_buf);
    fprintf(stderr, "[test_repo] using fixture: %s\n", repo);

    /* ── lcsas_repo_load_keys_dir: scan keys/ and decrypt with password ── */
    snprintf(path, sizeof path, "%s/keys", repo);
    rc = lcsas_repo_load_keys_dir(
        path, (const unsigned char *)FIXTURE_PASSWORD,
        strlen(FIXTURE_PASSWORD), &mk
    );
    if (rc != 0) {
        fprintf(stderr, "FAIL: load_keys_dir rc=%d\n", rc);
        return 1;
    }

    /* Master key should match the fixture's pinned bytes. */
    {
        size_t i;
        unsigned char expected_enc[32];
        for (i = 0; i < 32; i++) expected_enc[i] = (unsigned char)i;
        if (memcmp(mk.encrypt, expected_enc, 32) != 0) {
            fprintf(stderr, "FAIL: master key encrypt bytes mismatch\n");
            fails++;
        }
    }

    /* ── Wrong password must fail cleanly, NOT crash ──────────────── */
    {
        lcsas_master_key bad;
        rc = lcsas_repo_load_keys_dir(
            path, (const unsigned char *)"wrong-password", 14, &bad
        );
        if (rc == 0) {
            fprintf(stderr, "FAIL: wrong password accepted\n");
            fails++;
        }
    }

    /* ── Empty keys dir must fail ──────────────────────────────────── */
    {
        lcsas_master_key bad;
        rc = lcsas_repo_load_keys_dir(
            "/tmp/does-not-exist-keys",
            (const unsigned char *)FIXTURE_PASSWORD,
            strlen(FIXTURE_PASSWORD), &bad
        );
        if (rc == 0) {
            fprintf(stderr, "FAIL: nonexistent keys dir accepted\n");
            fails++;
        }
    }

    /* ── lcsas_repo_load_key_file directly ─────────────────────────── */
    {
        /* The keys/ dir has multiple files (stubs + the real key).
         * Walk the directory and find ONE that decrypts.  This also
         * implicitly exercises stub key files that fail MAC verification. */
        lcsas_master_key direct;
        char keyfile[1024];
        DIR *d;
        struct dirent *e;
        int found_real = 0;
        snprintf(keyfile, sizeof keyfile, "%s/keys", repo);
        d = opendir(keyfile);
        if (d) {
            while ((e = readdir(d))) {
                if (e->d_name[0] == '.') continue;
                snprintf(keyfile, sizeof keyfile, "%s/keys/%s",
                         repo, e->d_name);
                if (lcsas_repo_load_key_file(
                        keyfile, (const unsigned char *)FIXTURE_PASSWORD,
                        strlen(FIXTURE_PASSWORD), &direct) == 0) {
                    if (memcmp(direct.encrypt, mk.encrypt, 32) != 0) {
                        fprintf(stderr,
                                "FAIL: direct load_key_file mismatch\n");
                        fails++;
                    }
                    found_real = 1;
                    break;
                }
            }
            closedir(d);
        }
        if (!found_real) {
            fprintf(stderr, "FAIL: no key file in dir decrypted\n");
            fails++;
        }
    }

    /* ── lcsas_repo_load_key_file on garbage file ──────────────────── */
    {
        lcsas_master_key bad;
        FILE *f = fopen("/tmp/lcsas_garbage_key.json", "w");
        if (f) {
            fputs("{not valid JSON at all", f);
            fclose(f);
        }
        rc = lcsas_repo_load_key_file(
            "/tmp/lcsas_garbage_key.json",
            (const unsigned char *)FIXTURE_PASSWORD,
            strlen(FIXTURE_PASSWORD), &bad
        );
        if (rc == 0) {
            fprintf(stderr, "FAIL: garbage key file accepted\n");
            fails++;
        }
        unlink("/tmp/lcsas_garbage_key.json");
    }

    /* ── lcsas_repo_decrypt direct call ────────────────────────────── */
    {
        unsigned char plain[256];
        size_t plain_len = sizeof plain;

        /* Too short — must fail (data_len < 33). */
        unsigned char tiny[32] = {0};
        if (lcsas_repo_decrypt(&mk, tiny, sizeof tiny, plain, &plain_len) == 0) {
            fprintf(stderr, "FAIL: decrypt accepted <33-byte input\n");
            fails++;
        }
    }

    /* ── lcsas_repo_load_index: parse encrypted index, find blobs ──── */
    {
        lcsas_blob_index ix;
        const lcsas_blob_loc *loc;
        lcsas_blob_index_init(&ix);
        rc = lcsas_repo_load_index(repo, &mk, &ix);
        if (rc != 0) {
            fprintf(stderr, "FAIL: load_index rc=%d\n", rc);
            fails++;
        }
        if (ix.count != 6) {
            fprintf(stderr, "FAIL: index count=%zu, want 6\n", ix.count);
            fails++;
        }

        /* Find data blob */
        lcsas_hex_decode(FIXTURE_DATA_BLOB_HEX, 32, data_id);
        loc = lcsas_blob_index_find(&ix, data_id);
        if (!loc) {
            fprintf(stderr, "FAIL: data blob not in index\n");
            fails++;
        } else if (loc->is_tree) {
            fprintf(stderr, "FAIL: data blob mis-typed as tree\n");
            fails++;
        }

        /* Find tree blob */
        lcsas_hex_decode(FIXTURE_TREE_BLOB_HEX, 32, tree_id);
        loc = lcsas_blob_index_find(&ix, tree_id);
        if (!loc) {
            fprintf(stderr, "FAIL: tree blob not in index\n");
            fails++;
        } else if (!loc->is_tree) {
            fprintf(stderr, "FAIL: tree blob mis-typed as data\n");
            fails++;
        }

        /* Missing blob lookup. */
        {
            unsigned char missing[32];
            memset(missing, 0xFF, 32);
            loc = lcsas_blob_index_find(&ix, missing);
            if (loc != NULL) {
                fprintf(stderr, "FAIL: missing blob returned non-NULL\n");
                fails++;
            }
        }

        lcsas_blob_index_free(&ix);
    }

    /* ── lcsas_repo_load_snapshots ──────────────────────────────────── */
    {
        lcsas_snapshot_list snaps;
        long sidx;
        lcsas_snapshot_list_init(&snaps);
        rc = lcsas_repo_load_snapshots(repo, &mk, &snaps);
        if (rc != 0) {
            fprintf(stderr, "FAIL: load_snapshots rc=%d\n", rc);
            fails++;
        }
        if (snaps.count != 2) {
            fprintf(stderr, "FAIL: snap count=%zu, want 2\n", snaps.count);
            fails++;
        }
        sidx = lcsas_snapshot_latest(&snaps);
        if (sidx < 0) {
            fprintf(stderr, "FAIL: snapshot_latest returned -1\n");
            fails++;
        }
        /* snapshot tree should match fixture's tree blob */
        if (sidx >= 0
                && strcmp(snaps.items[sidx].tree_id_hex,
                          FIXTURE_TREE_BLOB_HEX) != 0) {
            fprintf(stderr, "FAIL: snapshot tree=%s want %s\n",
                    snaps.items[sidx].tree_id_hex, FIXTURE_TREE_BLOB_HEX);
            fails++;
        }
        /* snapshot_find by exact ID */
        if (sidx >= 0) {
            long found = lcsas_snapshot_find(&snaps, snaps.items[sidx].file_name);
            if (found != sidx) {
                fprintf(stderr, "FAIL: snapshot_find exact returned %ld\n", found);
                fails++;
            }
        }
        /* snapshot_find by short prefix */
        if (sidx >= 0) {
            char prefix[9];
            memcpy(prefix, snaps.items[sidx].file_name, 8);
            prefix[8] = '\0';
            if (lcsas_snapshot_find(&snaps, prefix) != sidx) {
                fprintf(stderr, "FAIL: snapshot_find prefix failed\n");
                fails++;
            }
        }
        /* snapshot_find missing returns -1 */
        if (lcsas_snapshot_find(&snaps, "deadbeefdeadbeef") != -1) {
            fprintf(stderr, "FAIL: snapshot_find missing returned !=-1\n");
            fails++;
        }
        lcsas_snapshot_list_free(&snaps);
    }

    /* ── empty snapshot_list latest returns -1 ─────────────────────── */
    {
        lcsas_snapshot_list empty;
        lcsas_snapshot_list_init(&empty);
        if (lcsas_snapshot_latest(&empty) != -1) {
            fprintf(stderr, "FAIL: latest(empty) should be -1\n");
            fails++;
        }
        lcsas_snapshot_list_free(&empty);
    }

    /* ── lcsas_repo_read_blob: full pipeline ──────────────────────── */
    {
        lcsas_blob_index ix;
        const lcsas_blob_loc *loc;
        unsigned char *blob = NULL;
        size_t blob_len = 0;
        lcsas_blob_index_init(&ix);
        if (lcsas_repo_load_index(repo, &mk, &ix) == 0) {
            loc = lcsas_blob_index_find(&ix, data_id);
            if (loc) {
                rc = lcsas_repo_read_blob(repo, &mk, loc, NULL,
                                          &blob, &blob_len);
                if (rc != 0) {
                    fprintf(stderr, "FAIL: read_blob rc=%d\n", rc);
                    fails++;
                } else {
                    const char *expect =
                        "hello from lcsas-restore fixture\n";
                    if (blob_len != strlen(expect)
                            || memcmp(blob, expect, blob_len) != 0) {
                        fprintf(stderr,
                                "FAIL: data blob content mismatch "
                                "(got %zu bytes)\n", blob_len);
                        fails++;
                    }
                    free(blob);
                }
            }
        }
        lcsas_blob_index_free(&ix);
    }

    /* ── lcsas_tree_restore: full end-to-end materialisation ─────── */
    {
        lcsas_blob_index ix;
        char target[] = "/tmp/lcsas_test_repo_target_XXXXXX";
        char hello_path[1024];
        char read_buf[256];
        FILE *f;
        size_t got;
        lcsas_blob_index_init(&ix);
        if (lcsas_repo_load_index(repo, &mk, &ix) != 0) {
            fprintf(stderr, "FAIL: load_index for tree restore\n"); fails++;
        }
        if (mkdtemp(target) == NULL) {
            fprintf(stderr, "FAIL: mkdtemp\n"); fails++;
        }

        rc = lcsas_tree_restore(
            repo, &mk, &ix, FIXTURE_TREE_BLOB_HEX, target, target,
            NULL, NULL
        );
        if (rc != 0) {
            fprintf(stderr, "FAIL: tree_restore rc=%d\n", rc); fails++;
        }

        /* Verify the file was created with correct content. */
        snprintf(hello_path, sizeof hello_path, "%s/hello.txt", target);
        f = fopen(hello_path, "rb");
        if (!f) {
            fprintf(stderr, "FAIL: hello.txt not created\n"); fails++;
        } else {
            got = fread(read_buf, 1, sizeof read_buf - 1, f);
            read_buf[got] = '\0';
            if (strcmp(read_buf, "hello from lcsas-restore fixture\n") != 0) {
                fprintf(stderr, "FAIL: hello.txt content: %s\n", read_buf);
                fails++;
            }
            fclose(f);
        }

        /* Sub-directory must be restored, with the empty file inside. */
        {
            char sub_path[1024];
            struct stat st;
            snprintf(sub_path, sizeof sub_path, "%s/subdir", target);
            if (stat(sub_path, &st) != 0 || !S_ISDIR(st.st_mode)) {
                fprintf(stderr, "FAIL: subdir not created\n"); fails++;
            }
            snprintf(sub_path, sizeof sub_path, "%s/subdir/empty.txt", target);
            if (stat(sub_path, &st) != 0 || !S_ISREG(st.st_mode)) {
                fprintf(stderr, "FAIL: subdir/empty.txt missing\n"); fails++;
            } else if (st.st_size != 0) {
                fprintf(stderr, "FAIL: empty.txt size=%lld, want 0\n",
                        (long long)st.st_size);
                fails++;
            }
        }

        /* Symlink: hello.txt's link.txt must exist as a symlink. */
        {
            char link_path[1024];
            struct stat lst;
            char link_target[256];
            ssize_t llen;
            snprintf(link_path, sizeof link_path, "%s/link.txt", target);
            if (lstat(link_path, &lst) != 0 || !S_ISLNK(lst.st_mode)) {
                fprintf(stderr, "FAIL: link.txt not a symlink\n"); fails++;
            } else {
                llen = readlink(link_path, link_target, sizeof link_target - 1);
                if (llen < 0) {
                    fprintf(stderr, "FAIL: readlink failed\n"); fails++;
                } else {
                    link_target[llen] = '\0';
                    if (strcmp(link_target, "hello.txt") != 0) {
                        fprintf(stderr,
                                "FAIL: link.txt -> %s (want hello.txt)\n",
                                link_target);
                        fails++;
                    }
                }
            }
        }

        /* Unsafe-named node ("../escape") must NOT have been created. */
        {
            char esc[1024];
            struct stat es;
            snprintf(esc, sizeof esc, "%s/../escape", target);
            if (stat(esc, &es) == 0) {
                fprintf(stderr, "FAIL: '../escape' was materialized!\n");
                fails++;
                unlink(esc);
            }
        }

        /* Unsupported chardev node must be skipped (not crash). */
        {
            char dev[1024];
            struct stat ds;
            snprintf(dev, sizeof dev, "%s/device.dev", target);
            if (stat(dev, &ds) == 0) {
                fprintf(stderr, "FAIL: chardev node was materialized\n");
                fails++;
            }
        }

        /* Re-run tree_restore: should be idempotent (Issue #92 resume).
         * The "already restored, skipping" code path in tree.c
         * (lines 114-119) must trigger because the target file exists
         * with the expected size. */
        rc = lcsas_tree_restore(
            repo, &mk, &ix, FIXTURE_TREE_BLOB_HEX, target, target,
            NULL, NULL
        );
        if (rc != 0) {
            fprintf(stderr, "FAIL: tree_restore re-run rc=%d\n", rc);
            fails++;
        }

        /* Wrong tree ID: must fail cleanly (no crash). */
        rc = lcsas_tree_restore(
            repo, &mk, &ix,
            "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
            target, target, NULL, NULL
        );
        if (rc == 0) {
            fprintf(stderr, "FAIL: missing tree ID accepted\n");
            fails++;
        }

        /* Progress reporting: rerun with progress enabled. */
        {
            lcsas_progress prog;
            char target2[] = "/tmp/lcsas_test_repo_target2_XXXXXX";
            lcsas_progress_init(&prog, ix.count);
            prog.enabled = 1;
            if (mkdtemp(target2)) {
                lcsas_tree_restore(repo, &mk, &ix, FIXTURE_TREE_BLOB_HEX,
                                    target2, target2, NULL, &prog);
                lcsas_progress_finish(&prog);
                /* Cleanup target2. */
                {
                    char cmd[1024];
                    snprintf(cmd, sizeof cmd, "rm -rf %s", target2);
                    (void)system(cmd);
                }
            }
        }

        /* Broken tree #1: file references a blob NOT in the index.
         * tree.c restore_file_node should hit the "blob not in index"
         * branch and return -1.  lcsas_tree_restore propagates the
         * failure (goto out → rc stays -1). */
        {
            char tdir[] = "/tmp/lcsas_test_broken_XXXXXX";
            if (mkdtemp(tdir)) {
                int rc2 = lcsas_tree_restore(
                    repo, &mk, &ix, FIXTURE_BROKEN_TREE_HEX, tdir, tdir,
                    NULL, NULL
                );
                if (rc2 == 0) {
                    fprintf(stderr,
                            "FAIL: broken tree (missing blob) should fail "
                            "but rc=0\n");
                    fails++;
                }
                {
                    char cmd[1024];
                    snprintf(cmd, sizeof cmd, "rm -rf %s", tdir);
                    (void)system(cmd);
                }
            }
        }

        /* Broken tree #2: file content has non-hex characters in a
         * 64-char string.  tree.c hex_decode returns -1 in
         * restore_file_node. */
        {
            char tdir[] = "/tmp/lcsas_test_bad_hex_XXXXXX";
            if (mkdtemp(tdir)) {
                int rc2 = lcsas_tree_restore(
                    repo, &mk, &ix, FIXTURE_BAD_HEX_TREE_HEX, tdir, tdir,
                    NULL, NULL
                );
                if (rc2 == 0) {
                    fprintf(stderr,
                            "FAIL: bad-hex tree should fail but rc=0\n");
                    fails++;
                }
                {
                    char cmd[1024];
                    snprintf(cmd, sizeof cmd, "rm -rf %s", tdir);
                    (void)system(cmd);
                }
            }
        }

        /* Broken tree #3: a dir node whose subtree is the broken tree
         * above.  lcsas_tree_restore recurses into the dir, the
         * recursive call fails, and the outer call goto-out's. */
        {
            char tdir[] = "/tmp/lcsas_test_bad_subdir_XXXXXX";
            if (mkdtemp(tdir)) {
                int rc2 = lcsas_tree_restore(
                    repo, &mk, &ix, FIXTURE_BAD_SUBDIR_TREE_HEX,
                    tdir, tdir, NULL, NULL
                );
                if (rc2 == 0) {
                    fprintf(stderr,
                            "FAIL: bad-subdir tree should fail but rc=0\n");
                    fails++;
                }
                {
                    char cmd[1024];
                    snprintf(cmd, sizeof cmd, "rm -rf %s", tdir);
                    (void)system(cmd);
                }
            }
        }

        /* Cleanup target. */
        {
            char cmd[1024];
            snprintf(cmd, sizeof cmd, "rm -rf %s", target);
            (void)system(cmd);
        }
        lcsas_blob_index_free(&ix);
    }

    if (fails == 0) printf("test_repo: OK\n");
    return fails ? 1 : 0;
}
